### ISSUE TITLE
DatePicker is not readed correctly after Chrome update

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-react#1017]
After last Chrome update the DatePicker spinner changes are readed incorrectly by NVDA: 'blank'.

Ticket: 1529519

**Comment by vdukic** [comment]
Do we have any updates here? Is it issue up to the chrome? I tried on Version 96.0.4664.45 (Official Build) (64-bit) and the issue still exists

**Comment by kspeyanski** [comment]
@vdukic May I please ask you to elaborate a little bit on the issue.

As we're revisiting this, I have a couple of questions, but first I want to clarify the following:
- We do not have a `spinners` property on the `DatePicker` component. The `spinners` configuration is available for the `DateInput` component only and it enables an `up` and `down` buttons which modify the currently selected part with a predefined step.

Are you using the `DateInput` component or do you refer to something else when you say `spinners`?

I would appreciate any assistance from your side, and I hope we can fix this in the upcoming weeks.

**Comment by vdukic** [comment]
Well, it is DatePicker component. I am using NVDA to read highlighted date (attached pic). I call that part spinner since you can change its value via arrows/mouse wheel :) and the reader narrates that as "blanc" instead of number/date. On some previous -v of chrome that works correctly. 
![image (22)](https://user-images.githubusercontent.com/17460856/144252532-33e962c3-4185-44f8-9600-56a5a21e0df3.png)
.

**Comment by kdikov82** [comment]
Tested with latest version of Chrome and NVDA 2022.4 and it announces the value correctly
