### ISSUE TITLE
Fix DateInput/DatePicker caret postion after focus.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1067]
Fix DateInput/DatePicker caret postion after focus.

Currently, if we have value it will select the full value on focus.

If there is a placeholder it will be positioned at the end of the value.

This creates inconsistencies.

More details + videos in ticket 1533644

**Comment by kspeyanski** [comment]
The issue has been fixed in `v4.10.0@dev` of the `@progress/kendo-react-dateinputs` package. 
Please check it out in our `Placeholder Demo` of the DateInput package, in our `development` site:
https://www.telerik.com/kendo-react-ui-develop/components/dateinputs/dateinput/placeholders/

Please let us know if you encounter any issues with the fix.

**Comment by Victorcorcos** [comment]
Hello Kendo Team!

I upgraded here my `@progress/kendo-react-dateinputs` to `v4.10.0@dev` and I noticed that this issue is **partially** fixed.

* When pressing the TAB key on keyboard to move over these Date Inputs, it is working. Please check the below video.

https://user-images.githubusercontent.com/7637806/135467839-0c1e5633-02cd-447a-b8ea-53f399fa9c2e.mov


* However, when directly clicking on these Date Inputs, the cursor is still being moved to the right side of the component. Please check the below video.

https://user-images.githubusercontent.com/7637806/135467497-00a05a5d-b92a-4f58-91d4-b4d3d31662d0.mov


### Could you guys also fix this?

Thanks you so much!

**Comment by kspeyanski** [comment]
Hello @Victorcorcos 

We're happy to hear that we're getting closer to fixing this and we really appreciate your feedback.
The behavior of the `focus-after-click` is intended, and we can not change this behavior at the moment. Please allow me to share more information.

When clicking in the DateInput, we're focusing the exact part which was clicked. E.g. if the user clicks on the `month` part we will select it. In the case where the user clicks in the far-right side of the input (shown on the second video) the default behavior of the browser would be to put the caret position at the end of the text, which we detect is closer to the `year` part, thus we're selecting in.

I can see that the `mask` of your dateinput is empty, and clicking on an exact part is not really possible. We acknowledge the fact that this is a valid scenario which we want to support with custom code, so I've prepared the following stackblitz example which demonstrates how can mouse click always result in selecting the first part:
https://stackblitz.com/edit/react-yw9s1d?file=app/main.jsx

I have made the example as simple as possible, but further improvements can be made depending on your application requirements like only focusing the first part on initial click, and applying this logic to the DateInput inside DatePicker.

Looking forward hearing back from you.
