### ISSUE TITLE
TreeView Animation error in strict mode

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#1083]
The following error exists when you click a TreeView item in strict mode:

![image](https://user-images.githubusercontent.com/40406043/133811165-7e12f4da-151b-4880-bbb3-c4cae8f8ebcb.png)

**Comment by Giacomo-ORS** [comment]
Hi, unfortunately this bug is not limited to TreeView but to all [Animations](https://www.telerik.com/kendo-react-ui/components/animation/): we noticed it while using Fade with Notification.

**Comment by silviyaboteva** [comment]
The problem comes from the older version of `react-transition-group` package. Once updated to `v4.4.2`, the warnings should disappear.

- Updated demo using the Animation package: https://stackblitz.com/edit/react-mghs85-qh9zfa?file=app%2Fmain.tsx
- Updated demo using the TreeView package: https://stackblitz.com/edit/react-vvizwt?file=app%2Fmain.tsx

We will update the dependency in our docs as well.
