### ISSUE TITLE
Add grouping to the DropdownList component

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-react#1094]
Currently, we have the grouping only for the ComboBox component:
https://www.telerik.com/kendo-react-ui/components/dropdowns/combobox/grouping/

**Comment by kdikov82** [comment]
Possible workarounds:
https://stackblitz.com/edit/react-8ucgjv-eygqr9?file=index.html
https://stackblitz.com/edit/react-8ucgjv-pgwmg2?file=app%2Fmain.jsx,index.html

**Comment by PekoPPT** [comment]
This functionality is already available since version [5.13.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#v5.13.0) of the KendoReact DropDownList. The DropDownList grouping demos can be found on [this link](https://www.telerik.com/kendo-react-ui/components/dropdowns/dropdownlist/grouping/).
