### ISSUE TITLE
Multi-day event not visible after switching to `Show full day`

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1125]
Multi-day event not visible after switching to `Show full day`.

Example: https://stackblitz.com/edit/react-eg4t5u-tldwuy?file=app/main.tsx

Steps:

1) Click `Show full day`
2) Noticed that the event is not shown even if it is part of this time window.

**Comment by kdikov82** [comment]
Most likely a related bug, which is replicated for business hours too (_in fact, in the initial example, if you go to "10/28/2021" and then go back to "10/26/2021" you will notice that the first event is missing in business hours_) 

Here is another very basic example where the event on "6/25/2021" disappears when you go to a future date (you can use the Next button to go to "6/26/2021") and then you return to "6/25/2021". It seems that the bug is replicated in business hours when you come from a future date:
[https://stackblitz.com/edit/react-rexryz-4gm2gv?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-rexryz-4gm2gv?file=app%2Fmain.jsx)

**Comment by kspeyanski** [comment]
The issue has been fixed in version `4.11.1` of the `@progress/kendo-react-scheduler` package.

Please refer to the changelog for the full list of changes in this version:
https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#be637ab5-74d0-5d30-b4cb-ecf78c7a32f2
