### ISSUE TITLE
Ie 9 Unable to get value of the property 'remove': object is null or undefined 

### ISSUE THREAD

**Issue by andalt** [telerik/kendo-react#114]
```
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/shim';
import 'raf/polyfill';

import React from 'react';
import { DatePicker } from '@progress/kendo-react-dateinputs';

const Search = () => (
    <div className="row">
        <div className="col-xs-6">
            <DatePicker />
        </div>
    </div>
);

export default Search;
```

--------------------------------------

"@progress/kendo-react-dateinputs": "^2.3.1",

![2018-11-01_15 33 44_4v2r5](https://user-images.githubusercontent.com/8655528/47852057-9912cf80-ddeb-11e8-9bd1-dc1c84c927bc.png)

**Comment by simonssspirit** [comment]
After a research, we noticed that the issue is because of a missing shim for a class list:

https://www.npmjs.com/package/classlist-polyfill

Still, after this is fixed there are other issues which we will have to inspect more closely.

Additionally, please have in mind that some of the component themes are using the new CSS flex styles, which are not supported in Internet Explorer 9:

https://www.telerik.com/kendo-react-ui/components/styling/ie9-support/

As the native React components will need more time investigated for the IE9 support, we can suggest checking our React wrappers:

https://www.telerik.com/kendo-react-ui/wrappers/dateinputs/datepicker/

**Comment by vladimirivanoviliev** [comment]
I can confirm that adding required polyfills resolves the issue.
