### ISSUE TITLE
Grid column virtualization does not work as expected

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-react#1147]
1. Header and data columns are not synced
2. Lagging while scrolling

<img width="609" alt="grig issue" src="https://user-images.githubusercontent.com/13251479/143568560-4ca96289-0ad8-44d0-ae22-661564b0eea5.png">

**Comment by vladimirivanoviliev** [comment]
This appears to be browser bug - Chrome calculate colspanned columns incorrectly - in following example the colspanned column have `149107.21875px` width where it should be `149100px` as the column width is specified to be exactly `150px`. When I disable the colspan the width of the table is working correctly. 

- https://www.telerik.com/kendo-react-ui-develop/components/grid/columns/column-virtualization/ 

Also this issue is not reproducible at all in Firefox.

**Comment by nstoychev** [comment]
Setting `display: block` style to the table magically resolves the issue - https://stackblitz.com/edit/react-rch9ye?file=index.html.
