### ISSUE TITLE
Unable to add list validation to kendo react spreadsheet. (Wrapper)

### ISSUE THREAD

**Issue by NebbiGIt** [telerik/kendo-react#115]
## I'm submitting a...

* Bug report 

## Current behavior

I am trying to add a list validation to kendo spreadsheet using kendo-spreadsheet-react-wrapper with react typscript. I get the following error when trying to add a list validation on a column of the spreadsheet. 

The error message i get is: **Error in /turbo_modules/@progress/kendo-ui@2018.3.1024/js/spreadsheet/customeditors.js (200:18).**

I forked your example from https://www.telerik.com/kendo-react-ui/wrappers/spreadsheet/ and reproduced the problem. 

**I found a solution to the problem by adding **var $ = kendo.jQuery** inside /node_modules/kendo-ui/js/spreadsheet/customeditor.js. inside my local project.**

**Inside customeditor.js**
![image](https://user-images.githubusercontent.com/40205267/47854529-3b2dba00-dde2-11e8-9ec3-ea37e2868abf.png)

## Expected behavior

Be able to use the list validation  on a cell or range of cells. 
## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/react-jkvyjq-1ezlpz?file=app%2Fmain.js

**Comment by NebbiGIt** [comment]
Hey @Xizario How long time will it take to fix this bug :) ?

**Comment by Xizario** [comment]
The issue happens when jQuery is not available for the whole window. It is not a problem in the wrapper itself.
Should not happen if the jQuery is loaded in the index.html, or simply pass it to the window in the constructor of your app to resolve it.
```js
  constructor(props) {
    super(props);
    window.$ = $;
  }
```
I originally tagged it with `wrappers` since it does not look to be KendoReact related issue. If there is problem with the spreadsheet, and it does not pass jQuery instance to it's templates, I would search for the public issues here: https://github.com/telerik/kendo-ui-core/issues?q=is%3Aopen+is%3Aissue+label%3A%22C%3A+Scheduler%22
