### ISSUE TITLE
Fix Calendar view after the year is changed.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1174]
Fix Calendar view after the year is changed.

Currently, the year will be cut. This occurs when choosing a year before the current one:

![image](https://user-images.githubusercontent.com/11087921/148219508-ec93cd73-f7a9-4961-a236-196ea902e6bb.png)

**Comment by kspeyanski** [comment]
This issue is related to: https://github.com/telerik/kendo-react/issues/1179

By design, the year (shown on the image) should not be visible at all (same as in `day` view) when navigating backwards.
When navigation through the left-side navigation, the view should align with the first focusable item in the calendar, in the above case - `Jan`.

We've fixed an alignment issue where there was a miscalculation of a couple of pixels which resulted in the above stated error. You can get the fix with version `4.14.0` of the `@progress/kendo-react-dateinputs` package.
