### ISSUE TITLE
Do not show the reorder clue when resizing the column.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1176]
Do not show the reorder clue when resizing the column.

When a Grid is both resizable and reordarable when we resize a column the reoder clue element will be shown. This may also lead to reordering the column during resizing.:

https://stackblitz.com/edit/react-nkn8sr-qdmn8u?file=app/main.tsx

**Comment by simonssspirit** [comment]
reported again in 1548953

**Comment by rickyoleary** [comment]
I am experiencing this issue too.

**Comment by kspeyanski** [comment]
The issue has been fixed with version `4.14.0` of the `@progress/kendo-react-grid` package. For the full list of changes, please refer to the [KendoReact Changelog](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#a04c4700-cebf-570e-8b74-a1601f6ddc15).

I'm closing this issue for now, but please let us know if you are still experiencing the issue.
