### ISSUE TITLE
Fix DatePicker months scroll when boostrap is not loaded.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1179]
Fix DatePicker months scroll when boostrap is not loaded.

Even if we use the default theme, removing the Boostsrap CSS will cause an issue with the month's scroll.

Steps:

1. Open the DatePicker.
2. Select a couple of months from the left navigation.
3. Notice how the position of the days is not aligned:

https://stackblitz.com/edit/react-pqycdj?file=index.html

**Comment by kspeyanski** [comment]
The issue has been fixed with version `4.14.0` of the `@progress/kendo-react-dateinputs` package: https://stackblitz.com/edit/react-pqycdj-ms3vsn?file=package.json. 

For the full list of changes, please refer to the [KendoReact Changelog](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#a04c4700-cebf-570e-8b74-a1601f6ddc15).
