### ISSUE TITLE
Prosemirror dependencies are locked to specific versions instead of a semver version range

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1215]
Currently, the Prosemirror dependencies in the Editor component are locked to specific versions rather than a semver range, which causes issues.
Ticked ID: 1553084

**Comment by lorena-caia** [comment]
We same the same problem on our project. Should we expect any changes soon? 
We are currently using the fix suggested [here](https://www.telerik.com/kendo-react-ui-develop/knowledge-base/editor-error-on-enter-press/ ) and it works. But, we need a proper fix on the @progress/kendo-react-editor in order to keep the packages easy up to date.

**Comment by nstoychev** [comment]
The prose-mirror packages dependencies are locked and we are updating them regularly. The update process includes running tests and testing for regression issues.

So far, we don't plan to change this process since we don't have control over the updates and cannot prevent any upcomming  issues.
