### ISSUE TITLE
Setting focus on the Kendo React Editor after form submitted and validation not passed

### ISSUE THREAD

**Issue by jrmcdona** [telerik/kendo-react#1281]
Is there a way to get a component ref to the Kendo React Editor?  I need to be able to set focus on the editor after my user clicks submit button and we run validation.    If our Editor does not pass validation,  we will have to reset the focus but I am not seeing how to do this currently with what is available.    Need to do this in React code.

Thanks

**Comment by jrmcdona** [comment]
Anyone?

**Comment by nstoychev** [comment]
Hi @jrmcdona,

I apologize for the late response.

Normally, you can pass props through the Field component props. But since passing ref does not work, you can use the editor's onMount event to get the editor's reference. See the following example - https://stackblitz.com/edit/react-tbtfwv?file=app%2Fmain.tsx.
