### ISSUE TITLE
The Tooltip does not show for Icon Button (unless you stop the pointer events for the icon)

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1296]
For some reason, the icon in the Button prevents the hover event to propagate to the Tooltip:

- [https://stackblitz.com/edit/react-s1uk75-suvdbq?file=app%2Fmain.tsx,app%2Fstyles.css](https://stackblitz.com/edit/react-s1uk75-suvdbq?file=app%2Fmain.tsx,app%2Fstyles.css)

The following can be used as a temporary workaround:
```
           .k-icon.k-svg-icon,
            .k-icon.k-font-icon  {
                pointer-events: none;
            }
```

**Comment by iadnonov** [comment]
Reported again in ticket: 1597722

**Comment by iadnonov** [comment]
Reported again in ticket: 1626923

**Comment by silviyaboteva** [comment]
I did some testing and reproduced the behavior using our [KendoReact Button component](https://www.telerik.com/kendo-react-ui/components/buttons/). It's an expected behavior and let me explain why.

Unlike the HTML `<button>` element, our Button component renders one `<button>` element with styles for the whole button and two inner `<span>` elements - one for an icon and one for the text. Hovering over the icon or text will not display the tooltip as the parent `<button>` element contains `title` attribute. The solution is using the [parentTitle](https://www.telerik.com/kendo-react-ui/components/tooltip/api/TooltipProps/#toc-parenttitle) property of the Tooltip component that will display the tooltip if any of the parent elements has a title.

Here is a demo showcasing the working tooltips by using `parentTitle` property:
https://stackblitz.com/edit/react-s1uk75-zfer72?file=app%2Fstyles.css,app%2Fmain.tsx
