### ISSUE TITLE
Rich Text Editor View HTML tool issue

### ISSUE THREAD

**Issue by love89music** [telerik/kendo-react#1298]
If it is not a issue for kendo please give a suggest to me that how to fix it. 
When I paste a whole html file into kendo react rich text editor view html tool, it miss the style in <head> tag.
Please try it with the first example in [kendo home website editor section](https://www.telerik.com/kendo-react-ui/components/editor/) 
## Current behavior
When use editor **VIEW HTML tool**, it miss the style between <head> tag. 
I debug it in browser.

**_1.It looks like **_kendo source code_** ignore style in html, which makes the style missing._**
**_2.Also the word between \<td>Peter<\/td> will parse to  \<td>\<p>Peter<\/p><\/td>_**,
**_which add a redundant \<p><\/p>_**

1. Is it possible to remove style out of ignoreTags.
2.  Also if we can add the style into it, Is it possible do not add additional \<p><\/p> into \<td>Peter<\/td>.

// : Object<bool> The block-level tags in HTML5
var blockTags = {
  address: true, article: true, aside: true, blockquote: true, canvas: true,
  dd: true, div: true, dl: true, fieldset: true, figcaption: true, figure: true,
  footer: true, form: true, h1: true, h2: true, h3: true, h4: true, h5: true,
  h6: true, header: true, hgroup: true, hr: true, li: true, noscript: true, ol: true,
  output: true, p: true, pre: true, section: true, table: true, tfoot: true, ul: true
};

// : Object<bool> The tags that we normally ignore.
var ignoreTags = {
  head: true, noscript: true, object: true, script: true, style: true, title: true
};

## Expected behavior
Do not miss the style in html <head> tag

## Minimal reproduction of the problem with instructions
- The first example in [kendo home website editor section](https://www.telerik.com/kendo-react-ui/components/editor/) 
-  click view html button in the first example.
- Then paste the html https://codepen.io/expertise/pen/XWZKqjw to the popup dialog, then save it you can see it miss the style between <head>

## Environment
Package versions: @progress/kendo-react-editor": "4.8.0"
I try it with lastest kendo version it has the same issue in [kendo home website editor section](https://www.telerik.com/kendo-react-ui/components/editor/) 

Browser:

- Chrome (desktop) version Version 100.0.4896.75 (Official Build) (64-bit)

System:
- TypeScript version: 4.4.4
- Node version: 16.14.0
- Platform:  Windows

**Comment by nstoychev** [comment]
Hi @love89music ,

The content of the editor has been validated according to its schema. See this article - https://www.telerik.com/kendo-react-ui/components/editor/schema/.

Since the style tag is not part of the schema nodes, it is stripped. Here is how to add the style tag - https://stackblitz.com/edit/react-1z75fv-cyy3gk?file=app%2Fmain.tsx

You can modify the schema and add the nodes that you need.

About the P tags in the TD, this is expected since the TD children should be block elements. The safest way to workround it is to strip those paragraphs after you get the HTML from the editor or before saving it to you database. If the problem is only visual, you can style those paragraphs (e.g. set them margin: 0 style) - https://www.telerik.com/kendo-react-ui/components/editor/styling-content/
