### ISSUE TITLE
Grid editing="date" is not opening the dropdown

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-react#1304]
The Grid with editing="date" should open the DaterangePicker dropdown.
The dropdown can not be opened because we are exiting the editing mode.

An example of the issue can be found here:
https://www.telerik.com/kendo-react-ui/components/grid/editing/editing-in-cell/ 
https://stackblitz.com/edit/react-gyb3dh?file=app/main.jsx

A workaround is to control the editing mode:
https://www.telerik.com/kendo-react-ui/components/grid/editing/editing-inline/
https://stackblitz.com/edit/react-mskuyg?file=app/main.jsx

**Comment by WissamProgress** [comment]
Reported it Ticket ID: 1597275

**Comment by WissamProgress** [comment]
Alro reported it Ticket ID: 1603107

**Comment by WissamProgress** [comment]
Since the DatePicker button triggers the blur event, and therefore `props.exitEdit` is executed inside the RowRender function, you can fire the exitEdit method only when the button is not clicked:
```
let flag = false;
const trProps = {
    ...props.tr.props,
    onClick: (e) => {
      if (e.target.classList.contains('k-button-icon')) {
        flag = true;
      }
    },
    onBlur: () => {
      !flag && props.exitEdit();
    },
  };
```
[https://stackblitz.com/edit/react-xvf943?file=app%2Frenderers.jsx](https://stackblitz.com/edit/react-xvf943?file=app%2Frenderers.jsx)
