### ISSUE TITLE
Changed GridColumn.displayName corrupt view of table

### ISSUE THREAD

**Issue by feonit** [telerik/kendo-react#138]
## Expected behavior
I want have the opportunity for do like this:
```js
Grid.displayName = "KendoGrid";
GridColumn.displayName = "KendoGridColumn";
```
but after that view of table is corrupt, because in
```js
<colgroup>
  <col {width}>
```

 param width not receive and possible lost somewhere above just for GridColumn

## What is the motivation or use case for changing the behavior?
I want to see in my storybook info panel jsx code with exactly "KendoGrid" word, not "KendoReactGrid".

## Environment
Package versions:
```js
    "@progress/kendo-react-grid": "2.4.0",
```

**Comment by Xizario** [comment]
I am okay for dropping the 'React' part of the `displayName`. But it will be breaking change and not sure how many people already relay on this right now. We could probably target it into `v3.0.0`

However, chancing it dynamically would still not be possible, since it is used for distinguishing the columns from other components inside the grid, pdf and excel export components.

**Comment by Xizario** [comment]
Any news or request about this, was it resolved by feature of storybook (since I suspect we are not the only one with hard-coded displayNames) or it is still on the table?
