### ISSUE TITLE
TimelineView does not send isWorkDay value to the custom slot properties

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1385]
The issue can be observed in the following example:
[https://stackblitz.com/edit/react-gqwwcg?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-gqwwcg?file=app%2Fmain.jsx)

The same works if the TimelineVIew is changed with WeekView.

**Comment by ivayloandonovprogress** [comment]
The issue has been fixed in [v5.6.0-dev.202208120836](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#c10ece15-9cd5-5267-b301-cd359dd3058d)

Demo: https://stackblitz.com/edit/react-gqwwcg-glxtjr?file=app/main.jsx

See the following article about obtaining the development builds - https://www.telerik.com/kendo-react-ui/components/installation/development-builds/.
