### ISSUE TITLE
Expose TimePicker setValue function

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#139]
## I'm submitting a...

* Suggestion for improvement

## Current behavior
There is no official way to manually update the TimePicker for uncontrolled components.

## Expected behavior
Either one of these options would be wonderful:

TimePicker.setValue(date);
TimePicker.value = date;

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-zphqrv?file=app/main.js
You can see in the HandleChange function, we're forced to use .setState({ value: value }) directly, which may be bypassing some internal logic we aren't aware of in the TimePicker component.

## What is the motivation or use case for changing the behavior?
We have a form with a lot of TimePicker components in the style of:

Monday: {TimePicker Start Time} {TimePicker End Time}
Tuesday: {TimePicker Start Time} {TimePicker End Time}
...

If the user chooses an invalid time e.g a Start time that is after the End time, we would like to allow the change but update the end time to match the start time for ease of use. This is currently a difficult operation.

Using controlled inputs with value={} causes performance issues as the entire page is re-rendered on keystroke so we would prefer to continue using defaultValue={}.

## Environment
Browser:
- Chrome (desktop) version 70.0.3538.110 (Official Build) (64-bit)

System:
- Node version: v8.9.3 6.4.1
- Platform:  Windows

**Comment by Xizario** [comment]
You can wrap the picker inside a component with state, and then reuse this component.
This way the picker will be controlled without rerendering the whole page, so it resolves the performance issue.

**Comment by Xizario** [comment]
Yes, wrap the picker and add setValue, then reuse the picker whenever it is needed. Here is modified version of your sample:
https://stackblitz.com/edit/react-zphqrv-rlpdyi?file=app/main.js

Now of course you can even name the 'MyTimePicker' to just 'TimePicker' and move it to another file to reuse it in the whole app.

You may ask me why we don't just give the method since it is already so easy? 
And the short answer is we want to be strict on the uni-directional flow, using the props as single source of truth, better transparency of the internal logic and easy extensibility. 

The first question that arrives when we discuss methods is: Should `onChange` be fired if `setValue` is used to change the value, and it is not an easy question.
