### ISSUE TITLE
Popup with position "right" and horizontal collision "flip" does not work as expected

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1423]
Opening the Popup in the following example with the current settings should flip the position from "right" to "left":

- [https://codesandbox.io/embed/silly-bhaskara-d3ew25?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/silly-bhaskara-d3ew25?fontsize=14&hidenavigation=1&theme=dark)

The same works correctly if the anchor element is on the left side with "position: left"

**Comment by nstoychev** [comment]
After investigating the problem, I found out that there are no sizes set to the Popover or its content and this is why the component fails to calculate its position.

In order to have proper position, set the width and height style to the content or the Popover: https://stackblitz.com/edit/react-8h7de4?file=app%2Fmain.jsx

**Comment by kdikov82** [comment]
Isn't it possible to get the rendered content and use its clientWidth/clientHeight to use them in the calculations? 

I came up a workaround, handling the onPosition event and manually correcting the "left" value, but I think we should be able to do this internally:

- [https://stackblitz.com/edit/react-8h7de4-wtuse4?file=app%2Fmain.jsx](https://stackblitz.com/edit/react-8h7de4-wtuse4?file=app%2Fmain.jsx)

**Comment by nstoychev** [comment]
Yes, it is possible and I made a PR.

**Comment by nstoychev** [comment]
Example with the fix (no size set): https://stackblitz.com/edit/react-8h7de4-btmlz4?file=app%2Fmain.jsx
