### ISSUE TITLE
Grid footer not exported to excel 

### ISSUE THREAD

**Issue by jiesu12** [telerik/kendo-react#1438]
Kendo React Grid doesn't export footers to excel.

See this example:
<https://codesandbox.io/s/interesting-cookies-fdis3j>

**Comment by kdikov82** [comment]
The Grid's column "footerCell" will not be used in the export, since the ExcelExport does not work with templates. Nevertheless, it is possible to overcome this by defining "footer" in the ExcelExportColumn as shown in the following examlpe and forum thread:
https://stackblitz.com/edit/react-bsahy6?file=app%2Fmain.jsx
https://www.telerik.com/forums/excel-export-of-footer-cells?_gl=1*rhwfcy*_ga*NTUwNzI3OTA4LjE1OTk0OTk0OTI.*_ga_9JSNBCSF54*MTY3NzMyNDk4My43ODUuMS4xNjc3MzI2MTg1LjYwLjAuMA..
