### ISSUE TITLE
Focus is not moving to next value automatically in kendo-react-dateinputs like input type date.

### ISSUE THREAD

**Issue by lokesh-shell** [telerik/kendo-react#1458]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Current behavior
Focus is not moving to next value mm(Ex: 31/mm/yyyy) automatically like input type date.

## Expected behavior
How can I set the focus to move automatically to the month after the date is entered and the focus moves to the year once the month is entered in a DatePicker ?

## Environment

Package versions:

```
[@progress/kendo-react-dateinputs@5.9.0](https://www.npmjs.com/package/@progress/kendo-react-dateinputs)
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by kdikov82** [comment]
This is the default behavior of the DateInputs, because there is no straight forward way to determine when the focus must move to the next part. For example, "2" is a valid date, but the user might want to set it to "22". The same applies for the month and the year.

Nevertheless, we can add a property that enables the automatic move to the next part in the cases where we can presume the entered value is the final one (for example 10/11/12 for month, 10+ for date)

**Comment by iadnonov** [comment]
With the latest version of the package, [v9.0.0-develop.9](https://github.com/telerik/kendo-react-private/releases/tag/v9.0.0-develop.9), the DateInput now provides different variants of utility properties for date and time configuration. By setting `autoSwitchParts`(by default, set to `true`), users can control switching between parts based on their preferences. 
The following example showcases this in the action: https://stackblitz.com/edit/react-wfp1td-fqzkuf?file=app%2Fapp.tsx

These new features will be included in our next official release.
