### ISSUE TITLE
kendo-react-editor - Can not convert <> to a Fragment

### ISSUE THREAD

**Issue by dsuchan** [telerik/kendo-react#1465]
## I'm submitting a...
I'm trying to use kendo-react-editor@^5.9.0 in react@^18.2.0 app. Anytime i press Enter or try to use OrderedList/UnorderedList tag, i get the `Can not convert <> to a Fragment` error in the browser console. After several reinstallations i realized that [you state peer dependency react@16.8.2](https://www.telerik.com/kendo-react-ui/components/editor/get-started/#toc-dependencies). When will be possible to use kendo-react-editor in react 18+ apps? Your examples from docs [that lead to StackBlitz](https://stackblitz.com/run/?file=app%2Fmain.tsx) use the exact same dependency versions as me and also shows the same errors in the console.

![image](https://user-images.githubusercontent.com/87578818/207853697-eb65ef7a-908c-47d1-a128-6e8bf4f48890.png)

**Comment by nstoychev** [comment]
The React version does not matter.

This happens because yarn and stackblitz cannot resolve the editor's dependencies correctly and install multiple versions of a single package.

If you open an example in StackBlitz, download it and run it locally, you will see that it works as expected.

For yarn, use [resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to specify which versions to be installed. For kendo-react-editor@^5.9.0, you can use the following:
```
resolutions: {
  "prosemirror-commands": "1.3.1",
  "prosemirror-history": "1.3.0",
  "prosemirror-inputrules": "1.2.0",
  "prosemirror-keymap": "1.2.0",
  "prosemirror-model": "1.18.1",
  "prosemirror-schema-list": "1.2.2",
  "prosemirror-state": "1.4.1",
  "prosemirror-view": "1.28.2",
  "prosemirror-dropcursor": "1.6.0",
  "prosemirror-gapcursor": "1.3.1",
  "prosemirror-tables": "1.2.5",
  "prosemirror-transform": "1.7.0"
}
```

**Comment by dsuchan** [comment]
Well, this works like as it suppose to. Thank you. I could not find that specific list of resolutions.

**Comment by nstoychev** [comment]
> I could not find that specific list of resolutions.

The resolutions list is from the package.json file of the `@progress/kendo-editor-common` package, which is a dependency of the `kendo-react-editor` package.
