### ISSUE TITLE
Changing the year in DatePicker often sets it incorrectly in React 18 with createRoot

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1630]
When changing the year in the DatePicker using createRoot and React 18 it is incorrectly set to 1911 or 1912. This can be reproduced in Chrome version 114.0.5735.134, however, this behavior is not reproduced in other version of Chrome:

https://stackblitz.com/edit/react-xc2oxm-n6stg2?file=app%2Fmain.tsx

Steps to reproduce:

1. Click the calendar button to open the calendar.
2. Click the month/year button to open the month/year selection.
3. Select any year

Note how the year in the month section of the calendar displays as different from the one shown when you hover over a month to select it.

![2023-06-01 16-22-07](https://github.com/telerik/kendo-react/assets/92358162/ca381a27-6bcc-4481-9bc2-ba4c12b719f3)

Ticket ID: 1611025

**Comment by kdikov82** [comment]
Similar issue can be observed in the following example when createRoot is used:
 - https://stackblitz.com/edit/react-ajetn7-npsqcr?file=app%2Fmain.jsx,index.html
1) Click on the "year"
2) Select new year from the left menu of the popup
3) Pick a month

The original year will be selected instead of the newly selected one.

**Comment by WissamProgress** [comment]
Reported in Ticket ID: 1616752

**Comment by elena-gancheva** [comment]
could be ralated to https://github.com/telerik/kendo-react/issues/1645

**Comment by iadnonov** [comment]
Fixed in 6.0.0 - https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#v6.0.0
