### ISSUE TITLE
[BUG][Grid] Unstable selection of embedded tables

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1643]
if we open a row it jumps to the table, however, when going back it is not possible to return to the table inside the cell. This can be reproduced in the following example with the following sequence:

Tab, down arrow, down arrow, Enter, down arrow, down arrow, down arrow,  Shift+Tab, Tab

or Tab, down arrow, down arrow, Enter, down arrow, down arrow, down arrow,  Shift+Tab,  up arrow, up arrow,  down arrow, down arrow, Tab.

https://stackblitz.com/edit/react-zydusu-vrau9y?file=app%2Fmain.tsx

Ticket ID: 1616095

**Comment by silviyaboteva** [comment]
This fix is included in version 8.1.0-develop.27. It will be available in the next official version.

**Comment by iadnonov** [comment]
I just wanted to add a quick note here. Accessing a detailed cell by using the `Tab` key is a side effect because when trying to access a detailed cell using the `Tab` key, it is important to note that the inner Grid has interactable elements that will be focused instead of the next focusable element, which in this case is the pager in the outer Grid. The correct way to access a detailed cell is by navigating to it using the arrow keys and pressing `Enter` when the detailed cell is focused to access its content. When you want to exit the detailed cell, press `Esc` and then continue with the arrow keys. For more information can be found on our [documentation page](https://www.telerik.com/kendo-react-ui/components/grid/interactivity/keyboard-navigation/)

**Comment by iadnonov** [comment]
The fix is available in our official version [v8.1.0](https://github.com/telerik/kendo-react-private/releases/tag/v8.1.0)
