### ISSUE TITLE
[Grid] Selection - Row reordering with selection does not allow dragging the rows

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-react#1671]
This issue can be reproduced when combining both of these demos:
[https://www.telerik.com/kendo-react-ui/components/grid/selection/](https://www.telerik.com/kendo-react-ui/components/grid/selection/)
[https://www.telerik.com/kendo-react-ui/components/grid/rows/row-reordering/](https://www.telerik.com/kendo-react-ui/components/grid/rows/row-reordering/)

When dragging a row for a second time, the drag animation will not start.

Related to Ticket ID: 1619441

**Comment by WissamProgress** [comment]
Also reported in Ticket ID: 1622365

**Comment by filipKovachev** [comment]
Here is an example that reproduces the issue from Ticket 1622316:

https://stackblitz.com/edit/react-8rerrr-frqekr?file=app%2Fdraggable-row.tsx

**Comment by zdravkov** [comment]
In order to have it working correctly we need to stopPropagation of the **handlePress**, **handleDragStart**, **handleDrag** and **handleDragEnd** events of the **DraggableRow** as for example it is done in this demo - https://stackblitz.com/edit/react-8rerrr-fsfusz?file=app%2Fdraggable-row.tsx,app%2Fmain.tsx,app%2Fdrag-handle-cell.tsx

This is needed to isolate the behavior from the internal drag and drop logic connected with the selection.
