### ISSUE TITLE
[Bug][MultiSelect] Virtualization is glitchy when using createRoot

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-react#1714]
When using virtualization with createRoot, scrolling becomes slightly glitchy instead of being smooth. This behavior does not occur with ReactDOM.render

Steps to reproduce:
1. Scroll slowly and notice that sometimes the scrolling glitches:
https://codesandbox.io/s/kendo-virtualization-problem-forked-g7mg9w

Ticket ID: 1625242

**Comment by WissamProgress** [comment]
Hi @bcacan I am really sorry for the late reply.

Here is an example that reproduces this bug with version 7.4.0 - https://stackblitz.com/edit/react-aagppy?file=app%2Fmain.tsx

However, we fixed it and the fix is now available in the latest dev version, and will also be available in the upcoming official release in May. You can test the dev version here:

- https://stackblitz.com/edit/react-4zkfv1-bc3ups?file=package.json
