### ISSUE TITLE
Grid details row action header

### ISSUE THREAD

**Issue by Nodios** [telerik/kendo-react#180]
## I'm submitting a...

* Bug report

## Current behavior
If you go [here](https://www.telerik.com/kendo-react-ui/components/grid/advanced-features/detail/) you'll see that there is a header element on the left of the Product header. This header space was not present in previous versions of Kendo.

## Expected behavior
This header should not be visible like in previous versions.

## Minimal reproduction of the problem with instructions
In official documentation [here](https://www.telerik.com/kendo-react-ui/components/grid/advanced-features/detail/) 

We do not have a way to remove that header if we want to have details row.

**Comment by simonssspirit** [comment]
@Nodios thank you for the report.

This occurs because the style is set inline to cover scenarios with the locked columns feature.

Currently, the color is based on the default theme, but we will make it dynamic for every theme.

Currently, a workaround can be used with CSS:

      .k-hierarchy-cell {
        background: white !important
      }

**Comment by Nodios** [comment]
Cheers, this is exactly what we did yesterday.

**Comment by Xizario** [comment]
The header of this functional column will not be removed, since it is semantically correct to be there. Official workarownd is to remove the `onExpandChange={this.expandChange}` from the grid's declaration, and then add custom column for expand collapse, in the custom column, it is possible to define custom header as well.
