### ISSUE TITLE
Unable to scroll in the selectable Grid on a mobile device

### ISSUE THREAD

**Issue by plevamatus** [telerik/kendo-react#1806]
## I'm submitting a...

* Bug report 

## Current behavior

When attempting to scroll down using gestures on a mobile device, the grid does not respond.

## Expected behavior

I expected scrolling to work.

## Minimal reproduction of the problem with instructions

  1. Open basic selection example from your documentation on mobile device: [https://www.telerik.com/kendo-react-ui/components/grid/examples/selection-basic/func/?theme=default-ocean-blue&themeVersion=7.0.2&env=prod](https://www.telerik.com/kendo-react-ui/components/grid/examples/selection-basic/func/?theme=default-ocean-blue&themeVersion=7.0.2&env=prod) 
  2. Uncheck **Enable drag selection** and **Enable cell selection** checkboxes
  3. Try to scroll down

## Environment

Browser:

- Chrome (Android) version 120.0.6099.115
- Safari (iOS) version 16.0

System:
- Platform:  Android, iOS

**Comment by WissamProgress** [comment]
Hi @plevamatus 
I would suggest using checkbox selection instead of row selection since row selection is not supported with mobile scrolling.
You can also toggle between checkbox selection and row selection depending on whether a mobile is used or not. In the following example, this is demonstrated using the `react-device-detect` package:
- https://stackblitz.com/edit/react-rnlmsj-4avkki?file=app%2Fmain.jsx

**Comment by plevamatus** [comment]
Hi @WissamProgress,
thanks for your answer, do you plan to implement row selection with mobile scrolling in near future?

**Comment by WissamProgress** [comment]
@plevamatus This feature is still in an unplanned stage, therefore, I can suggest adding a vote for it in order to increase its priority:
- https://feedback.telerik.com/kendo-react-ui/1590975-kendoreact-implement-the-ability-to-touch-drag-scroll-the-grid-rows-when-selection-is-enabled

Basically, we prioritize our upcoming features based on how much they are requested.
