### ISSUE TITLE
[Bug][Scheduler] SchedulerFormEditor does not provide an option for getting the default editor after the defaultProps are removed

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1816]
## I'm submitting a...
* Regression report

## Current behavior
SchedulerFormEditor.defaultProps is removed and and the default editors could no longer be used

## Expected behavior
There should be an option for using the default editors

## Minimal reproduction of the problem with instructions
Opening item for editing throws an error:
https://stackblitz.com/edit/react-utsejr?file=app%2Fmain.jsx

This is the KB article showing how to use the default RecurrenceEditor:
https://www.telerik.com/kendo-react-ui/components/knowledge-base/scheduler-recurring-event-in-form-editor/

## Environment

Package versions:
7.0.0 (7.0.2)
```

**Comment by kdikov82** [comment]
Reported in ticket: 1635527

**Comment by kdikov82** [comment]
Reported in ticket: 1635538

**Comment by WissamProgress** [comment]
Fixed in the latest dev version, and will be available in the upcoming official release:

- https://www.npmjs.com/package/@progress/kendo-react-scheduler/v/7.1.0-develop.7?activeTab=versions

After this fix, the defaultProps are now exported from `@progress/kendo-react-scheduler`. Here is an example of the implementation displayed in the description after the bug fix:

- https://stackblitz.com/edit/react-utsejr-tz51nm?file=app%2Fcustom-form-editor.jsx


## More info on this matter

The [defaultProps](https://legacy.reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values) were removed from the Scheduler in [7.0.0](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#v7.0.0) as a breaking change because they will be deprecated soon and showed a warning in Next.js. They were replaced by regular properties that we are now exporting from the scheduler package.

You can currently view all the available ones in the API page of the Scheduler on the develop branch:

- https://www.telerik.com/kendo-react-ui-develop/components/scheduler/api/
