### ISSUE TITLE
[Bug][PanelBar] Using expanded is not expanding the items initially

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#2105]
## I'm submitting a...
* Bug report 

## Current behavior
Setting initially expanded items to the PanelBar does not take effect as of version 4.14.0:
```jsx
<PanelBar expanded={['.1', '.1.1']} selected={'.0'} focused={'.1.1.3'} children={components} />
```

## Expected behavior
The items passes to the `expanded` prop has to be initially expanded like in v4.13.0:
https://stackblitz.com/edit/react-anekve-2v4d3v?file=app%2Fmain.tsx

## Minimal reproduction of the problem with instructions
1. Open https://stackblitz.com/edit/react-anekve-p7nzdz?file=app%2Fmain.tsx
Result: no items are expanded

## Additional details
Reported in Ticket ID: 1645160

**Comment by iadnonov** [comment]
As of version [4.14.0](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#v4.14.0) the expanded, selected and focused props take the item id as a value instead of the item title.

```jsx
<PanelBar expanded={['5', '7']} selected={'8'} focused={'11'} children={components} />
```

This behavior can be observed in the following example:
https://stackblitz.com/edit/react-anekve-jkxl4v?file=app%2Fmain.tsx

The description for the usage of the properties is described in detail in our next develop version [7.4.0-develop.10.](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#v7.4.0-develop.10) and will be affected at the public website as soon as possible.

**Comment by monamoghaddas** [comment]
@iadnonov Thanks for your example for workaround 
I made some adjustments to expand functionality on the fly. Initially, when I set the value, the expansion works, but subsequent changes don't seem to take effect. Do you have any suggestions for a workaround in this situation?
you can try this behaviour 
https://stackblitz.com/edit/react-anekve-69ly23?file=app%2Fmain.tsx

**Comment by iadnonov** [comment]
Hey [monamoghaddas](https://github.com/monamoghaddas),

If you want to use KendoReact PanelBar in [Controlled Mode](https://www.telerik.com/kendo-react-ui/components/layout/panelbar/controlled-mode/), you have to specify it with setting `isControlled` property to `true`.

I added this setup in the provided example:
https://stackblitz.com/edit/react-anekve-jk53wn?file=app%2Fmain.tsx 

Greetings, Ivaylo
