### ISSUE TITLE
[PDFExport] PDF Export has bugs when exporting svg that's styled with CSS

### ISSUE THREAD

**Issue by youngmoon715** [telerik/kendo-react#2119]
* Bug report

## Current behavior
* When exporting SVG into PDF, depending on how the SVG is styled, PDF is missing SVG styling.
* Inline-styling exports into PDF just fine (Recharts)
* CSS styling exports doesnt work (Mui x-charts)

## Expected behavior
* CSS Styling on SVG should also export correctly

## Minimal reproduction of the problem with instructions
1. Go to MUI Sample. Export. See that the colors are not added. MUI uses CSS to style their svg's.
2. Go to Recharts Sample. Export. See that colors are exported fine. Recharts uses inline-styling.

* [Mui Sample](https://stackblitz.com/edit/react-biuvdn?file=Demo.tsx)
* [Recharts Sample](https://stackblitz.com/edit/react-biuvdn-paaekk?file=Demo.tsx)

## What is the motivation or use case for changing the behavior?
Currently, my work around is to insert the styles inline by using useEffect into the SVG elements.

## Environment

Package versions:

```
@progress/kendo-react-pdf@5.11.0
@mui/x-charts@6.19.5
recharts@2.5.0
react-dom@17.0.2
react@17.0.2
```

Browser:
- Chrome (desktop) version Latest
- Firefox version Latest
- Safari (desktop) version Latest

System:
- TypeScript version: 5.0.2
- Node version: 18
- Platform: Mac

**Comment by PekoPPT** [comment]
Hello, @youngmoon715.
Thank you for the shared details about your scenario. After discussing the case with the team, I should say that the reported behavior is not a bug. It is a limitation in the PDF export functionality.

The solution I can suggest is to use the **KendoReact Chart** components instead of those you are currently using. 
You can check our [Chart - Exporting to PDF](https://www.telerik.com/kendo-react-ui/components/charts/chart/export-options/#toc-exporting-to-pdf) documentation for more details related to the PDF export of the KendoReact Charts.
