### ISSUE TITLE
Prevent tooltips to be displayed in mobile mode

### ISSUE THREAD

**Issue by baranseldinc** [telerik/kendo-react#2266]
Hi I am having trouble with tooltips. 

When users click on a `<button />` with title property a tooltip is being displayed on modal as you see picture below. 

## Current behavior
If a button with title prop is clicked tooltip is opened.

## Expected behavior
We can set tooltip behaviours conditionally (E.g. if user in mobile mode disable tooltips to be opened)

![image](https://github.com/telerik/kendo-react/assets/6670970/4eacbafb-a172-4e0e-87fe-79c336d3e01f)

Thanks for your attention.

**Comment by PaskalevStoyan** [comment]
Hi @baranseldinc,

Thanks for the opened issue. 

One viable option is to up the z-index of the Dialog Component so that it goes above the tooltip. 
The other option is to control the title attribute depending if the app is opened from a Desktop or Mobile. 

Keep in mind that without a reproducible demo, this is just a guess.

As this repository is exclusively dedicated to addressing bugs, handling feature requests, and discussing product enhancements i'll be closing this issue now but, If you need help with setting up a specific scenario or configuring a KendoReact component, please don't hesitate to open a ticket in our [support system](https://www.telerik.com/account/support-tickets).

**Comment by silviyaboteva** [comment]
Hello @baranseldinc,

In addition to my colleague's response, you can use a third-party logic to determine if the app is running on mobile and remove the title property of the button. You can check the code from the following KB article and the isMobile.jsx in particular, which provides a basic option for getting the result that you want:

[https://www.telerik.com/kendo-react-ui/components/knowledge-base/grid-selection-mobile-scrolling/](https://www.telerik.com/kendo-react-ui/components/knowledge-base/grid-selection-mobile-scrolling/?_gl=1*1xsxjlf*_ga*MTI5MTg5NjI4Mi4xNzE1NTQ1MTk4*_ga_9JSNBCSF54*MTcxNTgzNzg2NS41LjEuMTcxNTg0MDI4NC41OS4wLjA.*_gcl_au*MTcyODgyNzkwMS4xNzE1NTQ1MTk3)
