### ISSUE TITLE
Improve TabStrip performance when switching between taps.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#24]
Improve TabStrip performance when switching between taps.

Currently, if the animations are on, the TabStrip content will re-render multiple times.

Also, when we change taps, we are re-instantiating the components inside instead of re-rendering them.

**Comment by Xizario** [comment]
This should be optional as:
* Improving the performance on switching comes with worse initial load since all tabs would be rendered. 
* Rendering all tabs initially is not suitable for building wizard component.

It is not about the performance of the TabStrip, since the tab switches instantly. It is about the content that if heavy is rendered slowly, thus we could provide a way of instantiating all tabs in advance and hide them using css.

**Comment by dalingrin** [comment]
Agreed, optional would b best.

The issue I run into with re-instantiation is both because loading the data for some of my controls is a heavy duty operation and that the state of the control is reset. I could push the state out of said control but this isn't going to be trivial in my case. I am instead using Bootstrap's tabs for now.

**Comment by kspeyanski** [comment]
We've implemented the feature in-house and we will provide 2 options for how the tabs are mounted/unmounted:
* Every time you switch the tab, the old one will be unmounted, and the new one - mounted. (as it is currently working)
* Once a tab is mounted, it wont be unmounted until the whole `TabStrip` component is unmounted. Not-selected tabs will be hidden **but** will remain in the DOM. If a previously selected tab is selected again, a re-render will be triggered.

Both options will be triggered by a single property. We're looking for the most descriptive name for it, so we're open for suggestions.

**Comment by Xizario** [comment]
Added in `1.2.0`. [keepTabsMounted](https://www.telerik.com/kendo-react-ui/components/layout/api/TabStripProps/#toc-keeptabsmounted)

**Comment by gabsoftware** [comment]
With keepTabsMounted=true, why triggering a re-render? Why not just displaying the tab?

The issue of that re-render is that child components in the tab, whose internal states changed, are reset to default states.
