### ISSUE TITLE
Treelist implementation in Kendo React

### ISSUE THREAD

**Issue by IreneMarquet** [telerik/kendo-react#246]
Hi, 

We are searching for a component that implements a Treelist, as we want to create a nested table where the detail grid share the same headers as the master. Similar to this example:

https://demos.telerik.com/kendo-ui/treelist/index

Do we have the treelist library in Kendo React? How could we proceed to implement this functionality?

Thanks in advance.

**Comment by Xizario** [comment]
Hi @IreneMarquet , The TreeList is in our roadmap already, https://www.telerik.com/kendo-react-ui/roadmap/
And since May release is already a fact, we start implementing the TreeList soon. 

Could you share with us what are the most important features of a TreeList for you? We plan to be in pair with our previous suites, but customer feedback plays role in prioritizing the order of implementation.

**Comment by simonssspirit** [comment]
@IreneMarquet I'm glad to inform you that the TreeList is already in the dev channel and can be tested:

https://www.telerik.com/kendo-react-ui-develop/components/treelist/
