### ISSUE TITLE
Slider Animation not Working with Dropdownlist Component

### ISSUE THREAD

**Issue by vickypearce** [telerik/kendo-react#247]
## Current behavior
The Slider animation doesn't animate when you have a DropDownList as the child object. It just appears, works fine if you try to hide the dropdown though.

## Expected behavior
I'd like to act like when you put other things in the slider animation

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-ynpo1w

- Click the button, on show = true the dropdownlist just appears, on show = false the dropdownlist slides up gracefully

## What is the motivation or use case for changing the behavior?
The app I'm writing uses a lot of show/hiding on dropdowns based on specific behavior. A smooth transition between them would make it so much nicer for users. Also it

## Environment
```
Whatever you guys put on the demo documentation
```

Browser:
- Chrome (desktop) version  74.0.3729.131
- Firefox version Version 66.0.4
- Edge version - I tried to run this with Edge but it got a "out of stack space" error so I don't know if it actually works or not.

System:
- Platform:  Windows

**Comment by nstoychev** [comment]
@vickypearce - please, see how I modified the above example in order to work properly https://stackblitz.com/edit/react-ynpo1w-u3kabu?file=app%2Fmain.jsx

The problem is that if the DropDownList popup width or direction is not set, the component will calculate them using dropdown element.offsetWidth and getComputedStyle, and both cases will trigger page [reflow](https://gist.github.com/paulirish/5d52fb081b3570c81e3a), which will break the animation.

**Comment by vickypearce** [comment]
Thanks! I spent like two and half hours trying to get it work.
