### ISSUE TITLE
Grid - custom edit cell losing focus.

### ISSUE THREAD

**Issue by Nodios** [telerik/kendo-react#248]
## I'm submitting a...
* Bug report

## Current behavior

If you have custom edit cell for the GridColumn, upon edit, the component will lose focus after every keystroke/change

## Expected behavior

Custom edit component does not lose focus after every keystroke/change

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/react-cseiam
Created sample custom numeric text box component with min/max props. Passed the props for min/max. If you try to edit the value in the cell, you will be able to do it only once afterwards, focus is lost and you have to click again in the cell in order to edit further.

**Comment by simonssspirit** [comment]
@Nodios this occurs because the function is inside render and React will execute it each time which will lead to losing the focus.

I can suggest referencing the function outside of the render method and passing only the function reference to the cell prop.

This is the updated example: https://stackblitz.com/edit/react-cseiam-1fhuwt?file=app/main.jsx

**Comment by Nodios** [comment]
I was aware of the issue with the function. But couldn't get my head around it. Thanks for the tip tho! 🥇

**Comment by dgspurgin** [comment]
> @Nodios this occurs because the function is inside render and React will execute it each time which will lead to losing the focus.
> 
> I can suggest referencing the function outside of the render method and passing only the function reference to the cell prop.
> 
> This is the updated example: https://stackblitz.com/edit/react-cseiam-1fhuwt?file=app/main.jsx

Problem w/ this approach, though, is that if ANOTHER inline cell changes (Component B) - and as part of that change it updates the underlying data (think Redux) for Component A -- the grid reloads and focus stays on B but A's value, although its changed in data store, doesn't update in the UI.

**Comment by simonssspirit** [comment]
@dgspurgin I added a second cell and they are both updated :

https://stackblitz.com/edit/react-cseiam-1fhuwt?file=app%2Fmain.jsx

Is it possible to share an example reproducing the issue? I will be happy to take a look and advise.

**Comment by dyabol** [comment]
> @Nodios this occurs because the function is inside render and React will execute it each time which will lead to losing the focus.
> 
> I can suggest referencing the function outside of the render method and passing only the function reference to the cell prop.
> 
> This is the updated example: https://stackblitz.com/edit/react-cseiam-1fhuwt?file=app/main.jsx

And what, when i using hook API and generate tree of components dynamically by JSON. I need pass property to cell but i can't define it out of render function.

Something like additionalCellProps would be nice. 👍 
 
Thx.

**Comment by DheerajMahra** [comment]
@dyabol I am using functional component and facing the same issue as you mentioned. Can't define the function outside the component. Did you find a solution for it?

**Comment by dyabol** [comment]
> @dyabol I am using functional component and facing the same issue as you mentioned. Can't define the function outside the component. Did you find a solution for it?
> 
> @simonssspirit How can we handle this scenario in a functional component?

useMemo :-)

**Comment by simonssspirit** [comment]
The suggested approach is React.Context. We make the cell outside of the main component and pass the required props via React.Context. This can be seen in this demo in its Hooks version:

https://www.telerik.com/kendo-react-ui/components/grid/rows/row-reordering/#toc-built-in-browser-apis

**Comment by Beej126** [comment]
> [@dyabol](https://github.com/dyabol) I am using functional component and facing the same issue as you mentioned. Can't define the function outside the component. Did you find a solution for it?
> 
> [@simonssspirit](https://github.com/simonssspirit) How can we handle this scenario in a functional component?

for others landing here, instead of the React.Context approach, i want to offer proven success using "useCallback" wrapped around the custom cell definition function... i'm going to excerpt code from my current project to give basic direction... and if anyone lands here needing a full sample project please ask and i'll try to fit that in.

To me it seems pretty heavy to be defining a new React.Context for each additional custom cell requirement.

first, here's the beginning of a custom GridCell declared inside the main parent functional component, i.e. "hook based", with state dependencies coming from that parent, <mark>which is the core reason input focus becomes challenging</mark>... if you can declare your custom cell completely statically as another standalone function outside of any hooks parent, then you don't need to any of this.
```ts
    // eslint-disable-next-line react-hooks/exhaustive-deps
    const NumValueCell = useCallback(GenCell<ParmData>(p => ({
        content: props.parmDefsByParmStored?.[p.dataItem.parm_Stored]?.valueColumn !== "TEXT" ?
            <NumericTextBox value={p.value} onChange={p.onChange} {...SharedNumericTextBoxProps} />
            : undefined
    })), [props.parmDefsByParmStored]);
```
couple crucial aspects to make sure you align with:
- the dependency array must include any state variables that that the inner functionality needs to operate on... for example my parmDefsByParmStored here is data that comes from a web api fetch... if we do NOT tell useCallback to refresh the definition based on this dependency then it will capture the wrapped function at the very beginning BEFORE the data has been populated and the inherent closure of useCallback won't see any of that data... changing after the fetch is fine because after that it won't change again and the input widgets rendered inside the useCallback will therefore be stable
- the dependencies specified here can NOT be any state that changes from input widgets rendered inside the useCallback... anything like that would degrade those inputs to undesirable behaviors we're trying to avoid: losing focus, losing text input cursor position

after that we just assign the useCallback result to the cell property of a GridColumn:
```
<GridColumn field={nameof<ParmData>(p => p.numValue)} title="Raw Value" width={140} editable={true} cell={!!microSingularRegParmStored.current ? undefined : NumValueCell} />
```

and lastly, handle the onItemChange of the grid which through GenCell (see below) will receive the cell input widgets onChange events :
```ts
                        <Grid
                            isLoading={props.isParmDatasLoading}

                            data={parmDataResult.data}
                            dataItemKey={nameof<ParmData>(p => p.rowId)}
                            totalCount={totalParmDataCount}
                            total={parmDataResult.total}

                            dataState={parmGridDataState}
                            onDataStateChange={onParmGridStateChange}

                            onItemChange={onParmDataChange}
                        >...</Grid>
```

the Grid onItemChange handler is of course where each of us will go to town with our specific logic but here's an example of using the event properties to most efficiently update a backing object data array using the very handy new ES2023 "with" array method ... there are several newer array methods which update **immutably**... this "Array.with" approach leverages a small enhancement i suggested and KendoReact team has already incorporated into v8.4.0 (reference here: https://www.telerik.com/forums/data-grid-onchangeitem-griditemchangeevent---why-no-dataindex)
```
    const onParmDataChange = (e: GridItemChangeEvent) => {

        const updatedParm = new ParmData({ ...e.dataItem, [e.field!]: e.value, isDirty: true });
        setParmDataResult({
            total: parmDataResult.total,
            data: parmDataResult.data.with(e.dataIndex! - parmGridDataState.skip!, updatedParm) //nugget: nice! ES2023 finally brings in a method to copy & update array by index 
        });

        editingParmDataByRowId.current![e.dataItem.rowId] = updatedParm;
    };
```

"GenCell" is a helper i've built up over time and i recommend everybody considers using something like this... it encapsulates the recurring boilerplate overhead of putting widgets in a cell and passing those "onChange" back up to the grid's handler... besides providing cell content render, also convenient place to develop your own api for setting grid cell styling, title/tooltip and typical stuff that goes along with cell customization
```ts
/*
 * @param contentFunc - function that will be called to render cell. function receives the following input args that it can use to build content.
 * - dataIndex: the index of the row in the data array
 * - dataItem: the data item for the row
 * - field: the field name of the column
 * - value: the value of the field
 * - onChange: the output rendering of the content func can bind a widget to this onChange event, which will ulitimately fire out to the grid's onItemChange event where it can be handled by logic in the client page context 
 * @returns an object with these 3 properties:
 * - content: the content to be rendered in the cell
 * - toolTip: optional tooltip string
 * - className: optional class name to be applied to the \<TD> element
 * - style: optional style object that gets applied to the \<TD> element
*/
export const GenCell = <T,>(
    contentFunc: (contentProps: {
        dataIndex: number,
        dataItem: T,
        field: keyof T,
        value: any,
        onChange: (event: {
            value: any,
            /** passed through cell prop "syntheticEvent", which automatically propogates to grid onChange syntheticEvent as well */
            extraState?: any
        }) => void
    }) =>
        {
            content: React.ReactElement | string | undefined,
            toolTip?: string,
            addClassName?: string,
            style?: React.CSSProperties
        }
) =>
    (cellProps: GridCellProps) =>
        <GridCell {...cellProps}

            render={(defaultRendering, _cellProps) => {

                if (!cellProps.field) throw new Error("GenCell: required 'field' prop was not defined");

                const { content, toolTip, style, addClassName: className } = contentFunc({
                    dataIndex: cellProps.dataIndex,
                    dataItem: cellProps.dataItem,
                    field: cellProps.field as keyof T,
                    value: cellProps.dataItem[cellProps.field as keyof T],
                    onChange: (e: { value: any, extraState?: any }) => cellProps.onChange?.({
                        dataIndex: cellProps.dataIndex,
                        dataItem: cellProps.dataItem,
                        field: cellProps.field,
                        value: e.value,
                        syntheticEvent: e.extraState //yeah bit of a hack
                        //kendo support is adding dataIndex into this event object, just have to wait for that release: https://www.telerik.com/forums/data-grid-onchangeitem-griditemchangeevent---why-no-dataindex
                        // in the meantime i just did a few "patch-packages", see the "patches" folder in the root of the project
                        //save as plan b: syntheticEvent: { dataIndex: cellProps.dataIndex } as any,
                    })
                });

                return !defaultRendering ? <td className="k-table-td" /> :
                    React.createElement(
                        defaultRendering.type,
                        {
                            ...defaultRendering.props,
                            title: toolTip ?? (typeof (content) === "string" ? content : undefined), //if tooltip wasn't specified and cell content is just text, use that as the tooltip
                            className: [defaultRendering.props.className, className].filter(Boolean).join(" "),
                            style: { ...defaultRendering.props.style, ...style },
                            "data-grid-col-index": cellProps.dataIndex //nugget: see other comments, trying to clear the bits that block standard double click selection of cell text when we're in checkbox selection mode where drag selection is now enabled
                        },
                        content
                    );
            }}
        />;
```
