### ISSUE TITLE
[Bug] The KendoReact dependencies are not added when create-kendoreact-app is used

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#2550]
Public item - https://feedback.telerik.com/kendo-react-ui/1561911 

## I'm submitting a...

* Regression report 

## Current behavior

The dependencies for the KendoReact packages are not added tot he package.json file when a project is scaffolded with `create-kendoreact-app`.

## Expected behavior
The created project has to contain references for all KendoReact packages.

## Minimal reproduction of the problem with instructions

1. Follow the steps form this article - https://www.telerik.com/kendo-react-ui/components/getting-started/create-kendoreact-app/#toc-create-kendoreact-app
2. Open the created project and observe the almost empty package.json file:

```json
{
  "name": "my-test-ckra",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "cra-template-kendo-sass": "file:../../../.npm/_npx/b702a42a1b530dca/node_modules/cra-template-kendo-sass",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-scripts": "5.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "sass": "^^1.68.0"
  }
}

```

**Comment by joelparkerhenderson** [comment]
Thanks all for looking into this. What's the plan for an automated build test? Meaning, an automated test such that when a new Kendo release is being prepared, some automatic process happens that tries at least the basic test of "Does it set up?"

**Comment by silviyaboteva** [comment]
Hello @joelparkerhenderson,

Using the latest `v0.6.0` of the `create-kendoreact-app` package, the project is scaffolded, the dependencies are populated in the "dependencies" object of the package.json file, and the application builds and runs without errors. We have tested all configurations via the wizard and confirm that the produced application runs as expected. 

So, the solution is to upgrade the `create-kendoreact-app` package with the following command and test to scaffold a new project once again: 
```
npm install -g create-kendoreact-app@0.6.0
```

Please note that in case you choose to use SASS, there is the following warning:
```
Deprecation The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
```

This is expected and it won't break the application. Currently, the Kendo Themes are built on Node Sass syntax, but we already work on the Dart Sass migration (for reference: https://github.com/telerik/kendo-themes/issues/4104) and once we release it, it will resolve the warnings related to Sass.

Up to the question related to the automated build tests. We do have an automated build that checks if the project is created and builds successfully. This build runs daily.

I hope that the above information helps. 

I'm closing this issue and the one in our Feedback Portal as resolved.

**Comment by joelparkerhenderson** [comment]
Still not fixed-- please reopen.

The warnings now show:

```sh
Installing template dependencies using npm...
npm WARN deprecated npmlog@5.0.1: This package is no longer supported.
npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm WARN deprecated gauge@3.0.2: This package is no longer supported.
```

**Comment by silviyaboteva** [comment]
Hello @joelparkerhenderson,

From the code snippet, I noticed that these are warnings the will not prevent the application from building successfully. Can you confirm that the app builds and runs successfully without errors?

I did some further testing but I was not able to reproduce these on my end. So, I researched these packages and found out that they are coming from `@mapbox/node-pre-gyp` NPM package and they already have an issue opened on the matter: https://github.com/mapbox/node-pre-gyp/issues/877. You can track the status there. Once they merge the PRs of the dependabot, the warnings should disappear.

As a side note, can you please provide the configuration steps that are passed to the wizard when creating a new application and the output _package.json_ file so we can investigate further.

**Comment by joelparkerhenderson** [comment]
Hi Silvia, it sounds like your colleague is raising an even more-urgent point. Can you please clarify what you want?

Your colleague Vessy emailed me today and wants us to put the information in one place, not two places.

Here's from my email reply to him below... where do you want the info going please?

>  I noticed that these are warnings the will not prevent the application from building successfully. 

I don't know what that means-- using packages that are no longer supported is a GIGANTIC security risk, right?

Surely you're not accidentally trying to claim that Telerik is deliberately using packages that are no longer supported?

Unsupported packages in a current commercial release are a sign of engineering failures for most organizations, because of the security risks.

Can you please say yes/no/maybe if Telerik intends to fix/change/remove the unsupported packages in the near future?

###

Can you please clarify? Your team has previously directed me that the "one place" is in the Telerik feedback portal, and is NOT on GitHub. And I'm receiving this via email from your system, which for me is a third place. Are you now saying that you want that approach to flip-flop?

If so, can you please ask up your chain of command to clarify? This is because there's so much information missing from GitHub about Telerik and the relevant pieces of tech that I have to wonder if GitHub is better than the Telerick feedback portal for issues such as these.

**Comment by joelparkerhenderson** [comment]
This issue still is set as "Closed" which means I can't add more info-- can you reopen it?
