### ISSUE TITLE
kendo-react-upload: Is there a prop for changing "Select Files..."?

### ISSUE THREAD

**Issue by alxvallejo** [telerik/kendo-react#268]
Seems silly that I'm stuck with this "Select Files..." label on the upload button and not sure how to change it. Any suggestions

**Comment by Xizario** [comment]
All messages including the "select files" are localizable using the LocalizationProvider. Please refer to this article.
https://www.telerik.com/kendo-react-ui/components/upload/globalization/

Providers can be nested on into another, thus allowing you to change messages of specific component instead of the whole app if needed.

**Comment by Su-s** [comment]
how we can remove the select files label and add some other text

**Comment by vladimirivanoviliev** [comment]
Hello, as @Xizario already said you can use the globalization options of the Upload component to customize this message. Here is an runable example how to achieve this:
- [Demo](https://stackblitz.com/edit/react-ydqxsw?file=app/bg.json)
