### ISSUE TITLE
[Feature][DropDownList] Expose state properties via reference handle

### ISSUE THREAD

**Issue by bdbvb** [telerik/kendo-react#2720]
Hi. I just updated to KendoReact version 9.0.0. (Using TypeScript 5.6.3.)

Previously, inside of a particular event handler (on a span that wraps the DropDownList), I was getting a DropDownList ref and looking at the state property, as in the follow code snippet:

```
// open the filter popup when user starts typing
const wrapperOnKeyDown = useCallback((event: ReactKeyboardEvent<HTMLSpanElement>) => {
    // do nothing if not filterable or not a "printable" character
    if (!filterable || event.key == null || event.key.length !== 1 || event.ctrlKey === true || event.altKey === true) {
        return;
    }

    const list = getRefValue();
    // do nothing if list is not focused or list is already open
    if (list == null || !list.state.focused || list.state.opened) {
        return;
    }

    // open the list
    list.setState({ opened: true });
}, [filterable, getRefValue]);
```

In version 9, my ref needs to be a **DropDownListHandle**, but I'm no longer able to see the **state** property, so I'm having to cast the list to any, like so, to get at the **focused** and **opened** properties:

```
// open the filter popup when user starts typing
const wrapperOnKeyDown = useCallback((event: ReactKeyboardEvent<HTMLSpanElement>) => {
    // do nothing if not filterable or not a "printable" character
    if (!filterable || event.key == null || event.key.length !== 1 || event.ctrlKey === true || event.altKey === true) {
        return;
    }

    const list = getRefValue();
    if (list == null) {
        return;
    }

    // do nothing if list is not focused or list is already open
    const state: any = (list as any).state;
    if (!state.focused || state.opened) {
        return;
    }

    // open the list
    list.togglePopup();
}, [filterable, getRefValue]);
```

This seems to work, but obviously it's not ideal, and the state, focused, and opened properties aren't documented.

I'm not sure if the TypeScript definitions need to be updated for this, or if I should be getting that information a different way. 

If those properties are no longer accessible, then this would seem to be a breaking regression, in which case, can I get at those properties in a first-class manner?

Thanks for the assistance!

**Comment by PaskalevStoyan** [comment]
Hey, @bdbvb,

Thanks for the provided feedback, It's really helpful.

Firstly I want to say that we discussed this internally in our team and agreed to expose the requested state props.
Secondly, I would like to explain why this has happened, for you and for any future guys/gals who stumble upon this:

We are in the middle of transferring our components from class to functional. This being said, as they were once class components, they had inner reference to the `public (but hidden from our documentation)` / `protected (read-only mode)` methods / properties, and hence why access via reference was possible to these methods / props. As they weren't documented in our public API documentation, we didn't include them in the public reference that we expose via our component handles and this is the reason why this is not a breaking change but rather an feature request / enhancement.

We will try to release a version which will include these props as soon as possible.

**Comment by bdbvb** [comment]
Thanks for the update. Glad those will be included.

Just to give another perspective on whether this was a breaking change... although they may not have been in the documentation*, those properties were in the TypeScript typings and would therefore appear to the typical TypeScript user (who views the typings as published contracts, unless maybe there's a comment to the contrary on particular methods or properties) as "published" and usable properties. I would expect "internal-only" properties to be available in JavaScript but not described in the typings.

Just throwing that out there for perspective moving forward.


---
*When there's a version upgrade, the website documentation is updated right away to match the latest. Is there any way to look back at older versions of documentation? If not, that makes it difficult, for example, if someone wants to stay on an older version for a time, for whatever reason, especially when there are major breaking changes. But maybe that deserve a separate feature request.

**Comment by PaskalevStoyan** [comment]
Thanks for the feedback, @bdbvb. 
Firstly, I would like to touch base on the TypeScript / JavaScript mention in your comment:
Lets take the DateInput component for example as its still class component, in the process to be transitioned to a functional one.

When using the Type `DateInputHandle` our documentation says that you have access to the [following properties](https://www.telerik.com/kendo-react-ui/components/dateinputs/api/dateinputhandle). But when console logging the ref in an example like [this one](https://stackblitz.com/edit/react-x9vdpr?file=app%2Fapp.jsx) its observed that the component exposes more methods / properties than the `DateInputHandle` type intends to. This is because the component is still a `class component`  having an internal reference to its `protected / public` methods. 

In this line of words not all protected / public methods / properties are intended to land in our public API and here its our mistake that we expose more than intended. But as its not documented and people have found the internal methods / properties which are not documented, they are not intended for use and thus not being a breaking change if they disappear. 

As you give a valuable feedback, we will discuss it internally and correct accordingly if need be.

In addition each licensed customer of our KendoReact product has access to each and every previous version of the source code of the KendoReact product. More information can be found [here](https://www.telerik.com/kendo-react-ui/components/installation/source-code#:~:text=To%20obtain%20the%20full%20source,history%20of%20the%20official%20releases.&text=To%20update%20your%20clone%2C%20run,mirror%20repository%20is%20updated%20daily.).
