### ISSUE TITLE
Kendo React Editor: The Editor won't work in IE 10 mode

### ISSUE THREAD

**Issue by LetMeTryItOut** [telerik/kendo-react#282]
## I'm submitting a...
Issue regarding Kendo Editor module.
https://www.telerik.com/kendo-react-ui/components/editor/ 

If you access the above link in IE > set Emulation mode to IE 10.
We receive error as follows:
Unable to get property 'appendChild' of undefined or null reference

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Current behavior
Currently the issue persists in the latest version of Kendo Editor and it works in Chrome.
However, it works in IE edge mode, but not supported in IE 10.

## Expected behavior
It should render perfectly in IE, If not than probably is there any polyfill that can helps us out to make it working in IE 10

## What is the motivation or use case for changing the behavior?
Many sites around the globe are slowly migrating towards latest version of IE, but IE 10 still used heavily and Kendo Editor not working in that mode.

## Environment

Package versions:

```

```

Browser:
IE Version > Emulation mode IE 10

System:

It would be really helpful, if a fix is provided in upcoming version. As we couldn't find any polyfill that can do the task for us in IE 10 mode.

**Comment by Xizario** [comment]
In general we don't want to spend time in fixing IE related issues, since we already have the jQuery suite built around legacy browser support. It is fully functional and if you are targeting old platforms, using the wrappers should not be an issue: https://www.npmjs.com/package/@progress/kendo-editor-react-wrapper
https://docs.telerik.com/kendo-ui/third-party/react

We do make exceptions on IE11 since many corporations are using is as only available browser, but IE 10 is already dead.  
https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer
https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732
