### ISSUE TITLE
The PannelBar re-renders its child components onFocus and onBlur

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#285]
The PannelBar re-renders its child components onFocus and onBlur.

This can cause unexpected issues and performance issue due to the re-rendering.

This is an example showcasing the issue and how it can be fixed by preventing the events:

https://stackblitz.com/edit/react-n9m6sz?file=app/main.jsx

**Comment by kspeyanski** [comment]
This issue has bee fixed in v[3.5.0@dev](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#toc-350-dev201909271141) of the `@progress/kendo-react-layout` package.

I've updated the example, since stopping the propagation of the `focus` and `blur` events does not allow the PanelBar to stop the unnecessary re-renders.

https://stackblitz.com/edit/react-n9m6sz-6kxexj?file=app/main.jsx
