### ISSUE TITLE
Conditional Rendering not working for <MenuItem />

### ISSUE THREAD

**Issue by derencel20** [telerik/kendo-react#296]
So currently I have this component.

```
import React from 'react';

const ConditionalComponent = ({ children, display = true }) => display && children;

export default ConditionalComponent;
```

If I use this with MenuItem like this,

```
  <ConditionalComponent display={true}>
    <MenuItem text={i18n.t('Address label')} data="print_address_label" />
  </ConditionalComponent>
```

It still doesnt display.

### **Expected Behavior**
Render `<MenuItem />` if display prop of ConditionalComponent  is **true**

### **Actual Behavior**
The `<MenuItem />` doesn't render even though display prop is **true**

**Comment by simonssspirit** [comment]
This is expected because the MenuItems are not actual elements, they are used to allow declarative syntax for the Menu.  As the "ConditionalComponent" is not from the expected type it is ignored.

I can suggest using the standard React approach for showing items conditionally:

{ this.someVariable && <MenuItem text="Child item" />}

https://stackblitz.com/edit/react-zejpjg?file=app/main.jsx

**Comment by derencel20** [comment]
I see. Thanks.
