### ISSUE TITLE
setting default value not focussed in the datepicker 

### ISSUE THREAD

**Issue by niyaza3** [telerik/kendo-react#300]
## I'm submitting a...

* Bug report 

## Current behavior
defaultValue is set during the initialisation, while opening the calender it is not focussed and the calender shows with future month 

## Expected behavior
defaultValue is set during the initialisation, while opening the calender it is should focussed in the calender with respective month 

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-ys6vsz

## Environment

```

Browser:

- Firefox version  68.0 (64-bit)


System:
- Platform:  Windows

**Comment by simonssspirit** [comment]
@niyaza3 Thank you for the report. After testing I noticed that it occurs with defaultValue and value as well. It occurs only when there is a min date set. The data is correctly selected, but the Calendar is opened on an incorrect month.

We will plan the fix in our ToDo list.

**Comment by niyaza3** [comment]
@simonssspirit Thank you simmons , please let us know once it is resolved

**Comment by hamiltoncolyerlong** [comment]
Is there an update on this? This is a bit of a showstopper for the component in our use case.

**Comment by simonssspirit** [comment]
@kspeyanski Please take a look at this with priority.

**Comment by kspeyanski** [comment]
Hello @niyaza3 and @hamiltoncolyerlong ,

The issues has been fixed in the `@dev` version of the `@progress/kendo-react-dateinputs` package.

I've updated the package version in the provided stackblitz example: https://stackblitz.com/edit/react-ys6vsz-xpxzee?file=app/main.jsx

More information about obtaining development build can be found [here](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/)

Please let me know if you encounter any issues.

**Comment by niyaza3** [comment]
@kspeyanski  i tested with our application also , it works cool now, please keep us posted about the release date of V3.3.0

Thanks
