### ISSUE TITLE
Kendo React Grid does not support sorting with initialDirection option

### ISSUE THREAD

**Issue by tientrung92** [telerik/kendo-react#308]
When I use Kendo grid react wrapper I see a option `initialDirection` of `sortable`:
https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/sortable.initialdirection

But when I change to use Kendo React grid, I checked document, I don't see any option that is similar above: https://www.telerik.com/kendo-react-ui/components/grid/sorting/

So, Does Kendo team has plan to support `initialDirection` for Kendo React grid?

Thanks so much.

**Comment by Xizario** [comment]
At this point we are not planing to add initialDirection as configuration, since this can be implemented by inverting the direction of the sorting in the prop and in the event.
Here is an example:
```jsx
const reversedSort = sort =>
  sort.map(s => ({ ...s, dir: s.dir === 'asc' ? 'desc' : 'asc' }));
```
```jsx
        data={orderBy(products, this.state.sort)}
        sortable
        sort={reversedSort(this.state.sort)}
        onSortChange={(e) => {
          this.setState({
            sort: reversedSort(e.sort)
          });
        }}
```
And runnable sample: https://stackblitz.com/edit/react-lixteq?file=app/main.jsx
This approach can further be extended per column, thus potential is a bit better than the built-in version.

However if there are a lot of request about this, we can make it built-in.

**Comment by amandaluniz** [comment]
I would love to have this feature as well... The data already comes sorted by date in our case, and there's no way of displaying what's the sorted column by default

**Comment by Xizario** [comment]
@amandaluniz, You can use the `sort` prop of the grid initially will show to the user that given column is sorted. Later restore the same state if there is no actual sorting. Here is an example:

https://stackblitz.com/edit/react-uc2pko?file=app/main.jsx

**Comment by amandaluniz** [comment]
Thank you! That worked!
