### ISSUE TITLE
When a PanelBar has a child that has a float:left style, the panelbar does not animate

### ISSUE THREAD

**Issue by k290** [telerik/kendo-react#320]
## I'm submitting a...

* Bug report 

## Current behavior
If you include an element such as a` <div>` inside a panelbar with `float:left,` the panelbar doesn't animate correctly on expand and collapse. 

## Expected behavior
Animation should still work. 

## Minimal reproduction of the problem with instructions
See fork of demo:

https://stackblitz.com/edit/react-rvxfhl?file=app%2Fmain.jsx

## What is the motivation or use case for changing the behavior?
Floats are necessary especially for responsive design and comes up frequently. Animation gives a smooth user experience

## Environment

Package versions:
   "@progress/kendo-react-inputs": "^3.3.0",
    "@progress/kendo-react-intl": "3.3.0",
    "@progress/kendo-react-layout": "3.3.0",
    "prop-types": "15.7.2",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-router-dom": "5.0.1",
    "react-transition-group": "4.2.2"
Browser:

- Chrome (desktop) version 76

System:
- Platform:  Windows

**Comment by kspeyanski** [comment]
Hello @k290,

Please excuse me for the delayed response, but this was hell of an issue.

A simple solution will be to add a wrapping element with `style={{ overflow: "hidden" }}`, and the animation should work correctly. I'm attaching the modified example bellow:
https://stackblitz.com/edit/react-rvxfhl-x9j6hp?file=app/main.jsx

In case you find it interesting, i'm posting some explanation bellow.

The animation, in order for the [`Reveal`](https://www.telerik.com/kendo-react-ui/components/animation/types/#toc-reveal) animation to work, it must calculate the height of the container, since `css` animation from height 0% => auto/100% is impossible. This is actually the only animation that use additional JS calculation (in addition to css) in order to achieve the effect. This being said when the child have a `float` styling, the parent does not take the children's height.

Forcing the wrapping `div` to have the hight of a `float: left` children is what made it difficult to solve. While a sibling `clear: "both"` will make the parent to take the children height, but for some reason the DOM calculating returned `height=0`. I'm still find this hard to explain, but it seems that only `overflow: hidden` does fix the problem.

Once again, sorry for the delayed response and please let me know if the provided solution work.

**Comment by k290** [comment]
Hi Kiril. Yes the provided solution worked for us. The explanation about the heights is interesting. Thank you.
