### ISSUE TITLE
Window Component is not working with Animation

### ISSUE THREAD

**Issue by balag3** [telerik/kendo-react#326]
## I'm submitting a...

* Bug report 

## Current behavior

Window Component cannot be animated. Using any of the Animation types the Window is not displayed

## Expected behavior

Window openings and closings should be animated once the window component is wrapped in an animation component

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/react-8abpbx?file=app/main.jsx

## Environment

Browser:

- Chrome (desktop) version XX

System:
- Node version: v8.16.1
- NPM version:  6.4.1  
- Platform: Linux 

Once the Animation Component wrapper is removed from the above stackblitz demo (in this case `Slide`)
The Window component works properly.

**Comment by kspeyanski** [comment]
Hello @balag3,

Thank you for raising this issue. Due to the `absolute` positioning of the window and the `overflow: hidden` property of the animation container, animating the `Window` component with the `@progress/kendo-react-animation` package is not possible.

We will be working on a solution, but right now i can not give an estimate.

In the meantime i suggest a more basic `css` based approach for animating the `Window` component. Please take a look at the following stackblitz example and let me know if it suits your use case. 

https://stackblitz.com/edit/react-8abpbx-3pzbkc

Greetings

**Comment by balag3** [comment]
Hello @kspeyanski ,
Thanks for you fast response. I think the provided solution will be sufficient to continue working with Window. Wish success finding a solution though!
Cheers!
