### ISSUE TITLE
Grid custom range filter not working with Odata

### ISSUE THREAD

**Issue by IvanMitov** [telerik/kendo-react#355]
## Current behavior
When using a custom range filter through filterCell prop in combination with Odata server operations, on setting value in the filter (input), getting error: "filterOperators(...) is not a function" which comes from toODataString function. I`m thinking the reason is that the operator is a function, not a string.

## Expected behavior
Data should be filtered in the selected range without any errors.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/kendo-react-grid-rangefilter-bug

## Environment

Browser:

- Chrome (desktop) version 77.0.3865.120

System:
- Platform:  Windows

**Comment by simonssspirit** [comment]
@IvanMitov This occurs because in this case, the filter operation is a function.

A function call cannot be send the to oData server.

In this case, I can suggest a different approach.

To pass the filters for min and max to the standard filter expression and send that to the OData service.

The approach is similar to the date range filter in this example: https://stackblitz.com/edit/react-bjlym3-tzbypp?file=app/main.js

**Comment by IvanMitov** [comment]
@simonssspirit Thank you for the fast answer and that approach. It helped me make things work. 
I knew it had to be written in a similar way, but I wanted to make sure there was no easier solution. :)

I made example with working code which can help to people if they encounter such a problem: [https://stackblitz.com/edit/kendo-react-grid-rangefilter-bug-fix?file=app/main.jsx](url) (correct me if there is something wrong with the code)

In the future I would suggest you to mention in documentation that custom range filter isn`t supported for oData server and give some example with alternative. 

Thanks again and cheers!

Thank

**Comment by simonssspirit** [comment]
we made a kb for this https://www.telerik.com/kendo-react-ui-develop/knowledge-base/grid-date-ragne-filter/
