### ISSUE TITLE
Grid Master/Detail with virtual scrolling has small glitch

### ISSUE THREAD

**Issue by jarizast** [telerik/kendo-react#361]
## I'm submitting a...
* Bug report
* Suggestion for improvement

## Current behavior
Using the Virtual Scrolling combine with the Master/Detail example, it is hard to scroll up to the expanded first visible row.

## Expected behavior
scrolling up and down without any issue, even when any row is expanded.

## Minimal reproduction of the problem with instructions
  1. Go to this example https://stackblitz.com/edit/react-ehct6l?file=app%2Fmain.jsx
  2. Expand the first visible row
  3. Scroll Down (once or twice) when you can still see the detail of the first row
  4. Stop/Release Scrolling 
  5. Try to Scroll Up (it feels stuck)

## What may cause this issue?
I think that virtual scroll sync does not account for a row can be expanded and miscalculate everything based on an inaccurate percentage.

## Environment

Browser:
Chrome (desktop)

**Comment by jarizast** [comment]
Grid in Angular: https://www.telerik.com/forums/virtual-scrolling-and-detail-row-in-grid
Related: https://github.com/telerik/kendo-react/issues/299

**Comment by simonssspirit** [comment]
@jarizast When the Grid has detail rows, we recommend to not use the row height property as the height of the rows is not the same.

We are also considering adding the same option as in the Angular Grid, to have a detailRowHeight prop to better handle these cases.

**Comment by jarizast** [comment]
> @jarizast When the Grid has detail rows, we recommend to not use the row height property as the height of the rows is not the same.
> 
> We are also considering adding the same option as in the Angular Grid, to have a detailRowHeight prop to better handle these cases.

Removing **rowHeight** can fix this top scrolling problem but it causes other bigger scrolling issues at the bottom of the grid.

**Comment by simonssspirit** [comment]
This is reported one more time in the ticket: 1450232

This is another example: https://stackblitz.com/edit/react-bv1ara-olddpu?embed=1&file=app/main.jsx

Raising the priority.

@nstoychev  Please take a look at this when working on the virtualization updates.

**Comment by Xizario** [comment]
At this point the details need to be less than 50% of the height of the grid to allow smooth scrolling. 

The angular version of the component requires all the data (in other words: pure client binding) to be available in order to work. We don't want to pose such a restriction for the binding, because usually when it comes to huge data it is not available in the browser, but requested on chunks from the server, and this is what the virtualization is meant to handle. In case the data is small enough and already available on the client, it is better to render with regular scrolling.

Since the grid is not aware if the items outside the view are expanded or collapsed, it is impossible to fully calculate its scroll position. When the items(and their details) are small, there are adjustments that happen before rendering to minimize the scroll flickering. However when the items are big enough, they play significant part of the total scroll height, that can't be predicted if not knowing if these items will be expanded or collapsed when come into the view.

In such a cases, where the details are big enough to offset several items, and cover big portion of the grid,  the recommended approach will be to place the details inside the rows itself. (inside a cell, merged cells or using the row-render to override the whole row) This would equal to "all row details are expanded" thus making it predictable where the scroll should be. 
Another practical variation will be to show the details on a side of the grid, only for the selected item.
Alternative is also showing details inside a popup on user action.
