### ISSUE TITLE
Daterange picker value isn't updated

### ISSUE THREAD

**Issue by lukavuletic** [telerik/kendo-react#368]
Value isn't changed when manually entering numbers in the field, it only changes when selecting a presented date. When manually entering date, value remains null so reset is actually changing null to null, not the entered value to null.

Implementation of either reset button by default or a way to get value dynamically would solve the problem.

**Comment by kspeyanski** [comment]
Hello @lukavuletic ,

Could you please provide a [stackblitz](https://stackblitz.com/) example where the issues is reproducible?

By design the input fields in the DateRangePicker does not provide new value until a full date is entered. This is due to the inability to provide a partial Date object. Do you have any handlers that updates the state on input, which might be overriding the value of the DateRangePicker?

**Comment by lukavuletic** [comment]
Thanks for getting back at me. Here is stackblitz with the setup I am using.

https://stackblitz.com/edit/react-88yfyw?file=app%2Fmain.jsx

**Comment by kspeyanski** [comment]
Can you please elaborate on what exactly is the problem? To me the `DateRangePicker` is working as intended, but i'm missing what the desired behaviour is.

**Comment by lukavuletic** [comment]
https://i.imgur.com/QmwS2Mu.gif

As I wrote in the comment, initially writing partial date can't be reset. That is the problem I tried to elaborate.

**Comment by lukavuletic** [comment]
Version in use is "@progress/kendo-react-dateinputs": "3.2.2"

**Comment by kspeyanski** [comment]
Hello @lukavuletic,
Sorry for the delayed response. 
I will address the comments you left on the provided stackblitz example.

> 22: this should trigger on initially writing partial dates i.e. month/day/year > month/10/year

The default Javascript `Date` object does not support partial dates, and since we're using it for defining the `<DateInput />` value, we cannot trigger onChange without the user entering the full `Date`
This means we cannot trigger onChange when we only have the `day` part of the date.

> 27: this should remove partially entered dates

With the current set of features it is impossible to clear the mask, we were thinking abound exposing the mask to be controlled, but never received a feature request for it. Your use case seems valid and we will re-evaluate the feature. In the meantime you can log it as a feature request in our [feedback portal](https://feedback.telerik.com/kendo-react-ui?_ga=2.220952156.513925862.1578292666-1562087220.1574062841)

Even tho we does not support this feature at the moment, the desired behavior can be achieved through the [startDateInput](https://www.telerik.com/kendo-react-ui/components/dateinputs/api/DateRangePickerProps/#toc-startdateinputsettings) and [endDateInput](https://www.telerik.com/kendo-react-ui/components/dateinputs/api/DateRangePickerProps/#toc-enddateinput) properties of the `DateRangePicker`.

I've extended the provided stackblitz example to clear the input values on reset button click:
https://stackblitz.com/edit/react-e1dm1b?file=app/main.jsx

Please let me know if you need further assistance, and once again, excuse me for the delayed response.

Greetings

**Comment by lukavuletic** [comment]
Thank you for your response. Reset button now does remove partially entered date which is great, but, try to reproduce these steps please.

https://imgur.com/a/JX2oyi9

As you can see, upon manually entering some value, if you click onto another field it instantly brings up the old value. What can be done about that?

Meanwhile I will log a feature request!

**Comment by kspeyanski** [comment]
Hello @lukavuletic,

I've updated the stackblitz example here: https://stackblitz.com/edit/react-l5uasg?file=app/main.jsx

Please find the code added on lines 87 and 90. With this additional logic, the mask should be updated permanently!

Please let me know if you need further assistance.

**Comment by lukavuletic** [comment]
That solves the issue completely for now! Thanks a lot for your provided assistance.

- Best regards, Luka!
