### ISSUE TITLE
Image is not coming in the pdf when react is converted to pdf

### ISSUE THREAD

**Issue by KkartikSsharma** [telerik/kendo-react#418]
[doubt.txt](https://github.com/telerik/kendo-react/files/3955552/doubt.txt)

please check the above file....m not able to get the image in the pdf

**Comment by simonssspirit** [comment]
@KkartikSsharma Please check the following article as the images have to be hosted on the same domain in order to be in the PDF:

https://www.telerik.com/kendo-react-ui/components/drawing/limitations-browser-support/#toc-cross-origin-resources

_Images that are hosted on different domains are exported only if the server provides permissive Cross-Origin HTTP headers. Similarly, fonts might not be loaded across domains. Even with the proper CORS headers, Internet Explorer 9 is not able to load images or fonts from another domain and might raise a security exception. If your application supports Internet Explorer 9, make sure that you host images and fonts on the same domain as the application._

**Comment by nitinmcsam** [comment]
with out using CORS Headers how to download image with pdf

**Comment by Xizario** [comment]
@nitinmcsam Host the images in the same domain and CORS will not be needed.
