### ISSUE TITLE
Treelist norecords

### ISSUE THREAD

**Issue by SMaverick78** [telerik/kendo-react#458]
Hello! 
The screenshot shows that the number of td colspan is missing.

![norecords](https://user-images.githubusercontent.com/15866632/73157819-4d84c980-40f3-11ea-8d8d-aa3b58aab5bb.PNG)

How can I add the missing amount of td colspan to norecords?

https://stackblitz.com/edit/react-grrsjx?file=app%2Fmain.jsx

**Comment by simonssspirit** [comment]
@SMaverick78 Thank you for reporting the issue, the fix is on pull request and should be merged soon.

Please have in mind that we reward [Telerik points](https://www.telerik.com/community/telerik-points) for reporting issues. In order to receive the points please choose one of the following:

1- Open the future bug reports in our [support system](https://www.telerik.com/account/support-tickets)

2- leave the email that holds the license for KendoReact inside the issue and I will add the points to that account.

**Comment by nstoychev** [comment]
@SMaverick78 - We have published a fix in our [dev channel](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-3110-dev202001271052). Here is the above example updated - https://stackblitz.com/edit/react-grrsjx-stwekt?file=app/main.jsx.

**Comment by Xizario** [comment]
Fixed in `3.11.0`
