### ISSUE TITLE
Grid custom column menu disappears when I change to another tab and get back

### ISSUE THREAD

**Issue by Nassefferjeni** [telerik/kendo-react#470]
I'm using the kendo Grid custom column menu and I am following the documentation: https://www.telerik.com/kendo-react-ui/components/grid/columns/column-menu/

The problem is that I don't have enough control over the custom column component, meaning I can't know what action triggers the opening of the custom column menu ( onOpen/ OnCustomColumnOpen), is there a boolean that I can set when I change the browser to another tab and get back I can have the custom column menu open.

**Comment by simonssspirit** [comment]
@Nassefferjeni Currently, there is no such option.

I can offer to make this as a feature request and we can introduce it in a later version.

**Comment by kdikov82** [comment]
The ColumnMenu will be closed after some action within it or if the focus moves outside of it (on blur). In the described scenario, the menu will be closed due to the fact that it is blurred. This means that there is no way to make a distinguish if the menu was blurred because another tab was opened or if another element in the same view was focused. In both cases, the focus will move to a different element. Another issue with the requirement is that the blur event fires before the focus event, which makes getting the target of the clicked element impossible (unless setTimeout is used, but this could not be added in the Grid as a built-in functionality).
