### ISSUE TITLE
[PDF Processing]Automatic page break doesn't work with manual page break

### ISSUE THREAD

**Issue by aksgupta14** [telerik/kendo-react#482]
## I'm submitting a...

* Bug report 

## Current behavior

The automatic page break is ignored if we have manual page break set.

## Expected behavior

The automatic page break should be honoured and the elements should not be truncated.

## Minimal reproduction of the problem with instructions

With force page break
https://stackblitz.com/edit/react-ivpecb-igbxbg?file=app/main.jsx

With automatic page break
https://stackblitz.com/edit/react-ivpecb?file=app/main.jsx

## What is the motivation or use case for changing the behavior?

When you enter a force page break, you still expect your components to stick together. Like consider a very big paragraph with heading and you can see the stackblitz example as well. 
## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX

System:
- TypeScript version: 3.7.4 
- Node version: 12.15.0  
- Platform: Mac

**Comment by Xizario** [comment]
Place an empty tag when you want to break the page. 
```<p className="page-break" />``` between your paragraphs. 
Here is modified version of your code:
https://stackblitz.com/edit/react-ivpecb-zt8li5?file=app/main.jsx

**Comment by aksgupta14** [comment]
What if the content is dynamic and there is a page break on the parent element, the child page break is ignored.
Please consider the below example.
https://stackblitz.com/edit/react-ivpecb-rfhpak?file=app/main.jsx

**Comment by Xizario** [comment]
Nesting paragraph tags is invalid HTML. https://www.w3.org/TR/html401/struct/text.html#h-9.3.1

The example below shows how to use page breaks when you need them. The idea is that you don't need to set it for the element that have children, rather than element that is self-closing. Similar to how new page separator works in MS Word.

Assuming you load recursive content, in `div` rather than paragraph, you can still break page when you need it using self-closing tags like `br`, `a` or `span`.

https://stackblitz.com/edit/react-ivpecb-am6jdv?file=app/main.jsx

If this is not the use case, please give us further example how you load the text and on what condition the page breaks should be, so we can look for a solution.
