### ISSUE TITLE
Grid grouping does not persist when changing pages

### ISSUE THREAD

**Issue by ryancole** [telerik/kendo-react#500]
## I'm submitting a...

* Bug report

## Current behavior

When using the Grid and grouping, with pagination enabled, the groups do not persist across page changes.

## Expected behavior

I'd expect that once a user collapses a group, that group remains collapses even while moving from page to page.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/react-5vwty7?file=app%2Fmain.jsx

This is a fork of one of your grouping examples. Simply collapse a group and change the pages back and forward. The collapsed state of the groups is completely lost.

## What is the motivation or use case for changing the behavior?

Users would expect that when collapsing groups that they would remain collapsed until they expand them again.

**Comment by simonssspirit** [comment]
@ryancole  This is because the expanded state has to be kept in the state as well.

We have an example that showcases how this is done, using the TreeList mapTree method as the grouped data is a tree as well.

We will consider removing the method from the TreeList and adding it to a common package:

https://stackblitz.com/edit/react-2ots26-rwa3br?file=app/main.jsx

**Comment by InaGlushkova** [comment]
We have similar enhancement request under ticket - 1469219.

The issue comes from grouping on multiple levels. When we expand/collapse inner section it is collapsing all of that kind. For more details, please check the [code example here](https://stackblitz.com/edit/grid-grouping-selection?embed=1&file=app/main.jsx).

**Comment by simonssspirit** [comment]
We have a new method that helps with this case. The demo can be seen here: https://www.telerik.com/kendo-react-ui/components/grid/grouping/#toc-persist-groups-collapsed-state
