### ISSUE TITLE
Plot band line not appearing

### ISSUE THREAD

**Issue by larkiny** [telerik/kendo-react#521]
I am trying to get custom plot bands working, and I cannot get your demo to show the plot band line. I can see it in your example here: 

https://www.telerik.com/kendo-react-ui/components/charts/chart/elements/plot-bands/#toc-custom-plot-bands

when using both Chrome latest or Brave latest. However, when I open the Stackblitz linked in the example, I cannot see the plot band line. The code between your example and the Stackblitz is identical as far as I can tell. My only guess is that your example is using different versions of libraries than the Stackblitz project? In any case, I am unable to get any custom plot bands to show on any Kendo React chart. I've spent hours on this and I've given up. There is clearly a bug in your Drawing library.

Browser: Chrome 80.0.3987.132
System: MacOS Catalina

**Comment by simonssspirit** [comment]
@larkiny thank you for the report.

I will check it in more detail and follow up.

The text part of the drawing is shown, only the line is missing, which means the general drawing logic is working.

**Comment by simonssspirit** [comment]
@larkiny we found that the issue occurs because of the way StackBlitz is handling the dependencies. As the drawing is part of the charts, this leads to two versions of the drawing package being loaded and one of the internal checks fails.

This should not occur in a real project.

Please check if you have this issue also locally in a real application?
