### ISSUE TITLE
Form validator ignore default values

### ISSUE THREAD

**Issue by Thalandor** [telerik/kendo-react#617]
## I'm submitting a...

* Bug report 

## Current behavior

Current form validator ignores default value of an input field.

## Expected behavior

Form validation should take into account the initial value of the inputs.

## Minimal reproduction of the problem with instructions

Use the example below:
https://stackblitz.com/edit/react-wf5veh

If you try to submit the form the validator pops in and shows an error, even when the default value is a valid mail. You need to actually change the field so the validator 'understand' the current value.

## What is the motivation or use case for changing the behavior?

Sometimes we have default values on inputs where the form validation shouldn't pop in because the default value provided is perfectly correct. However, once the user focus the field for whatever reason, the validator shows directly an error message even if its a correct value.

## Environment

Package versions:

```

```

Browser:

- Firefox version 76

**Comment by InaGlushkova** [comment]
The issue, does **not** exist.

If we have initial values for some Form fields, we have to use [initialValues](https://www.telerik.com/kendo-react-ui/components/form/api/FormProps/#toc-initialvalues) property. When we add the wanted default values as part of the `initialValues` prop value, the data is submitted correctly. The Form Field component does not have `defaultValue` property.

For more details, please check the following example:
[https://stackblitz.com/edit/react-wf5veh-mr1ha4?file=app/main.jsx](https://stackblitz.com/edit/react-wf5veh-mr1ha4?file=app/main.jsx)

--

API reference to the KendoReact form Field component:
[https://www.telerik.com/kendo-react-ui/components/form/api/FieldProps/](https://www.telerik.com/kendo-react-ui/components/form/api/FieldProps/)

API reference to the KendoReact Form component & `initialValues` property:
[https://www.telerik.com/kendo-react-ui/components/form/api/FormProps/#toc-initialvalues](https://www.telerik.com/kendo-react-ui/components/form/api/FormProps/#toc-initialvalues)

**Comment by ryancole** [comment]
> The issue, does **not** exist.

Hello @InaGlushkova. I know this is an old github issue, but I believe the issue did exist and does still exist. In your code sample, you added an additional input field which completely changes the original poster's intention.

The original poster was making an example in which the form is already completely filled out by the initial values. In some case, a form might start off with some pre-filled data and that data might all be valid and acceptable. The user may not need to change the data before hitting submit. Exactly like in the original poster's example.

In the original example, the user did not realize that the initial values were supposed to be on the Form component, though. So I have provided an adjusted code sample below where the form still only has 1 field and the default values are provided via the Form component.

https://stackblitz.com/edit/react-wf5veh-reyjj3?file=app/main.jsx

You can see in this code above that Form is still preventing the submission due the validation or something.

To me, without understanding the underlying code, it looks like validation needs to run if initial values are provided so that the Form realizes that there is already valid data present.

**Comment by InaGlushkova** [comment]
Hello @ryancole,
The above issue was related to the error which apeared when you are not using the `initialValues` property of the Form.

About the Form submition - this is the intentional implementation of the Form. The Form component is not allowing the sumbition if none of the Fileds is modified.

I have opened a new feature request about the Form submition without the initial values modification.
Please check the status here:
https://github.com/telerik/kendo-react/issues/975
