### ISSUE TITLE
Add scroll to index helper method to the Grid.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#643]
Add scroll to index helper method to the Grid.

The goal is to provide an easy option to scroll to a specific item inside the Grid. This is can be really helpful in virtual scrolling cases where there are thousands of items.

Currently, it can be achieved using this approach, but it has some limitation:

https://stackblitz.com/edit/react-fznnqq-7fwr87?file=app/main.jsx

**Comment by simonssspirit** [comment]
Also requested in 1474372

**Comment by simonssspirit** [comment]
Also requested in 1477051. The goal here is to set initial skip of the Grid and to scroll to the correct position, as currently the scroll is at the top and this provides wrong skip and first scroll.

**Comment by simonssspirit** [comment]
requested again in 1483340

**Comment by Nodios** [comment]
@simonssspirit this would be very helpful. are you planing on adding this?

**Comment by simonssspirit** [comment]
@Nodios  We are planning to provide a method (built-in or not) that will make this more available. We are planning to deliver it by the end of this release (mid-January) or one of the first things in the next release based on how the already tasks are moving.

**Comment by abeggchr** [comment]
We are waiting for an improvement in this area since June (ticket 1473049) and I'd like to express my dissatisfaction with postponing the issue again. We were expecting a solution "by December". We are approaching our products first release in the middle of February and this has to be working.

**Comment by abeggchr** [comment]
In order to speed things up I'd like to share a draft of yet another workaround (see attached VirtualGrid.tsx file). Since we are only using a limited set of Grid features, we were able to create a proof-of-concept of a Grid component with virtual scrolling which does not have the `scrollable` property set to `virtual`. The 'selectedId' property is comparable to the 'scrollToIndex' property this issue is about because this component automatically scrolls to the selected item. I hope this gives you an input when resolving this issue.

There is one question though: How risky would you say the attached workaround is for future updates of the Kendo React library?
[VirtualMainGrid copy.tsx.txt](https://github.com/telerik/kendo-react/files/5695884/VirtualMainGrid.copy.tsx.txt)

**Comment by Xizario** [comment]
@abeggchr There is no risk for the attached solution to work with future versions, here is an example with slider.
https://stackblitz.com/edit/react-fznnqq-spsoqb?file=app/main.jsx
You can use it for production, if it was actual blocker we would have been prioritized it earlier.

**Comment by Nodios** [comment]
@Xizario What about scenarios where total item count can/will changes? You have in your code a call to reset when totals don't match. In my case I had to add one more line to the above solution (I don't know how good it is yet but it seems to be working)

```
this.gridRef.vs.total = newCount;
this.gridRef.vs.container.scroll(0, index * step);
```

**Comment by Xizario** [comment]
@Nodios The scroll resets when the total is changed. This is done by default, because usually the total changes when people use filtering which completely changes the visible items. 

Do you need the scroll to stay on the same position? If so this is quite possible and we can add this as an option (to skip the internal reset)

Here is refactored example, where the code is in static method, so it can be reused without hard-coded heights and does not depend on the app state. https://stackblitz.com/edit/react-fznnqq-qjcnnl?file=app%2Fmain.jsx
If this is the required behaviour, please confirm and we will make it built-in.

**Comment by Nodios** [comment]
@Xizario I agree. 

Yes, we do need the scroll to stay at the position, this is why I used the snippet above.

**Comment by vladimirivanoviliev** [comment]
Same requested for Treelist / Gantt, ticket #1500028. @nstoychev

**Comment by abeggchr** [comment]
As mid-January is approaching fast, when can we expect an enhancement or a workaround?

**Comment by simonssspirit** [comment]
The developer is already working on the task and working on covering the edge cases. This final ETA will depend on how long it tasks to resolve the edge cases.

**Comment by abeggchr** [comment]
That's great to hear! Is there already a dev version available to try it?

**Comment by Xizario** [comment]
`scrollIntoView` was added in `v4.5.0` for Grid, TreeList and Gantt

**Comment by abeggchr** [comment]
Great! I tried it with version `4.5.0-dev.202103070821`. It works (almost) as expected and certainly tackles the problems we described in support ticket 1473049.

I allow me to give you feedback about the thing that does not work as expected: The method is called `scrollIntoView()` and what it does is: it scrolls the grid so that the given `rowIndex` is on the first row of the visible grid. What I expect is, that the function only scrolls, when the given `rowIndex` is not visible (or: "_in the view_"). 

What we are doing is we first determine whether the item is visible and only call `scrollIntoView()` when it's not visible. That looks as follows:

```
  useEffect(() => {
    if (selectedId) {
        const virtualContent = document.getElementsByClassName(gridId)[0].querySelector(".k-virtual-content")!;
        const rowsInVirtualContent = virtualContent.clientHeight / defaultRowHeight;
        const indexInPage = data!.findIndex(i => i.id === selectedId);
        const visible = indexInPage > 0 && indexInPage < rowsInVirtualContent;
        if (!visible) {
          const rowIndex = sortedAndFilteredItems.findIndex(dto => dto.id === selectedId);
          gridRef.current?.scrollIntoView({ rowIndex });
        }
      }
    }
  }, [selectedId, gridRef]);

```

What I assumed is that I can write was something (nicer) like:

```
  useEffect(() => {
    if (selectedId) {
          const rowIndex = sortedAndFilteredItems.findIndex(dto => dto.id === selectedId);
          gridRef.current?.scrollIntoView({ rowIndex });
      }
    }
  }, [selectedId]);
```

So either the name of the method could be changed (i.e. changed to `scrollToShowItemOnTop()` or similar) -
OR the functionality could be changed, so that it only scrolls when the item is not yet _in the view_ (I certainly prefer the later).

Maybe there is also a way to control the scrolling behavior similar to the options that can be passed to [element.scrollIntoView()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView).

**Comment by Xizario** [comment]
Further item for the extended options: https://github.com/telerik/kendo-react/issues/964
