### ISSUE TITLE
Scheduler editor form multiple resources editor (MultiSelect) scrolling not working.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#648]
Scheduler editor form multiple resources editor (MultiSelect) scrolling not working.

Detailed steps + example is available in ticket 1473836.

**Comment by InaGlushkova** [comment]
Requested again in ticket: 1477121.

**Comment by kspeyanski** [comment]
Since version `3.16.0` of the `@progress/kendo-react-scheduler` package, the issue is not reproducible.
It seems it was a combination of a couple of issues related to the Scheduler Editor, which were resolved in `3.16.0`.

I'm going to close this issue for now, but feel free to reopen it in case the it is still reproducible in any version above (or equal to) `3.16`
