### ISSUE TITLE
Month is clipped in the date picker for material UI

### ISSUE THREAD

**Issue by gerrod** [telerik/kendo-react#66]
## I'm submitting a...
* Regression report

## Current behavior
The date picker clips rendering of the month using the Material theme.

## Expected behavior
The month should be visible

## Minimal reproduction of the problem with instructions
See: https://www.telerik.com/kendo-react-ui/components/styling/theme-material/
Scroll down to the date picker; notice that the month is clipped:

![image](https://user-images.githubusercontent.com/865932/44559012-a3c93c80-a78a-11e8-96ee-a67f191aa38a.png)

## What is the motivation or use case for changing the behavior?
We use the material theme

Browser:
- Chrome (desktop) version 68.0.3440.106
- Edge version 42.17134.1.0

**Comment by kspeyanski** [comment]
Hello @gerrod ,

Thank you for reporting this bug. The fix is already live in our `dev` channel, and soon will be published as version `1.3.0` of the `@progress/kendo-react-dateinputs`.

Please refer to the [`obtaining development build`](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) article for more information about the `dev` channel.

From the attached image i can see you are using an old version of the `@progress/kendo-theme-material`, please update it to `1.2.0` to avoid further problems with the styling of our components.

**Comment by gerrod** [comment]
Hi @kspeyanski - The bug is definitely still present in `1.2.0`.

* I assume the [Telerik website which talks about styling](https://www.telerik.com/kendo-react-ui/components/styling/theme-material/) is running the latest 1.2.0 build, and the bug is present there - that's where the attached image came from.

* [Here's a StackBlitz](https://stackblitz.com/edit/react-yfi5a2) that also reproduces the bug using the `@dev` build for the material theme (`1.3.0-dev.ec89ce55`) with the `1.2.0` build for the dateinputs. **Note** changing the `@progress/kendo-react-dateinputs` to the `@dev` build solves the bug.

**Comment by kspeyanski** [comment]
Hello @gerrod ,

The styling example in the website is running an old version of the components, thank you for bringing this to our attention, we will update it to use the latest version.
The bug is fixed only in our `@dev` channel and we will be releasing an official version `1.3.0` of `@progress/kendo-react-dateinputs` soon, so you won't have to use the `@dev` anymore in order for the calendar to visualise properly.

Please let me know if you need further help.
