### ISSUE TITLE
Cannot select a text inside inputs components if they are placed inside a Sortable.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#683]
Cannot select a text inside inputs components if they are placed inside a Sortable:

https://stackblitz.com/edit/react-npq12w-x982bf?file=app%2Fmain.jsx

This occurs because we prevent the default event internally:

https://github.com/telerik/kendo-react-private/blob/develop/packages/sortable/src/Sortable.tsx#L417

**Comment by sschuerle** [comment]
We have exactly the same problem. Support ticket already issued and got a reference to this issue.

My questions on these issue are: 
What is the actual state/status and will this issue actually be fixed in the next update release?
(The question relates to the fact that this issue is already nearly a year old and is still open.)

Thanks in advance for further clarification ^^

**Comment by Xizario** [comment]
It is fixed in 4.8.0 https://stackblitz.com/edit/react-8u1kpz
