### ISSUE TITLE
The Checkbox component will not update its checked state if the state value is changed from outside.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#699]
The Checkbox component will not update its checked state if the state value is changed from outside.

Steps to reproduce:

1) Click the checkbox - this will uncheck it.
2) Click the button that will change the state value - the Checkbox remains unchecked:

https://stackblitz.com/edit/react-hxbpec?file=app/main.jsx

If you do not click the checkbox before clicking the button, clicking the button will change the Checkbox value correctly.

This also affects its behaviour in Forms:

https://github.com/telerik/kendo-react/issues/650

**Comment by silviyaboteva** [comment]
Reported again in ticket ID: 1497347

**Comment by silviyaboteva** [comment]
Reported again in a ticket with ID: 1503907

**Comment by baks** [comment]
We also noticed this bug. In our scenario we have checkbox in column header, which we want to select/deselect all checkboxes in column.
But, due to that bug data displayed on frontend side is wrong.

Our minimal repoduction example of this bug with functional components is here: [https://codesandbox.io/s/serene-jackson-lrc2i?file=/src/Parent.tsx](url)

@silviyaboteva, I didn't know that this is already logged. Thanks for raising priority for this!

**Comment by silviyaboteva** [comment]
Fixed in [`v4.5.0`](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#0efc49cf-fb41-5e8f-9773-5fc4a4663e58).
