### ISSUE TITLE
Value not changed in NumerictextBox with custom formats and selecting the full value.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#735]
Value not changed in NumerictextBox with custom formats and selecting the full value.

Use this demo for tests:

https://www.telerik.com/kendo-react-ui-develop/components/inputs/numerictextbox/formats/

Steps:

1) Select the value in the Decimal NumericTextBox and press 1 - The value is changed to 1.00.
2) Select the value in the Currency with format options NumericTextBox and press 1 - The value is not changed.

**Comment by simonssspirit** [comment]
After more tests, we saw that it is not reproduced constantly.

Please contact me when start working on the issue.

**Comment by Xizario** [comment]
Cool [Observer effect](https://en.wikipedia.org/wiki/Observer_effect_(physics)), issue does not reproduce during screen sharing. Probably caused by some race condition and depends on machine performance.

**Comment by vladimirivanoviliev** [comment]
After deeper investigation of the video of the issue it appears that the reason for current behavior is that double click in Chrome for some reason selects not only the number part but the space character between the format and the numbers:
![image](https://user-images.githubusercontent.com/2195951/94895382-fd38e500-0493-11eb-8251-f0fc612ae37a.png)
In this case when the user presses some number in the change event I receive the following:
`4euros`
When I try to search inside this value for the defined format I'm not finding it as you actually deleted 1 symbol from the format. Here is a good place to explain why I'm not ignoring the space symbol for this search - the reason is that there are formats in which this space is special symbol (such example is Bulgarian culture where this symbol is `String.fromCharCode(160)`). I will investigate further if it's possible to improve current behavior by start ignoring this symbol while checking if current value is valid.

Also as a valid workaround I would suggest users to start selecting the full value (including the format symbols) or strictly the numbers if they need to replace it:
![image](https://user-images.githubusercontent.com/2195951/94896123-6e2ccc80-0495-11eb-898e-442c6b276e6c.png)
![image](https://user-images.githubusercontent.com/2195951/94896136-7553da80-0495-11eb-9325-09f1d6dadadd.png)

**Comment by kdikov82** [comment]
After testing this with the latest version (5.10.0) multiple times and on different browsers, I was not able to replicate the problem.
