### ISSUE TITLE
Kendo React Charts (PIE) does not render properly if number of items for the legend is high

### ISSUE THREAD

**Issue by tybshahid** [telerik/kendo-react#744]
![image](https://user-images.githubusercontent.com/34671914/94843024-71a56100-045f-11eb-84c6-9c5cb16e2746.png)

**Comment by tybshahid** [comment]
![image](https://user-images.githubusercontent.com/34671914/94843490-1b84ed80-0460-11eb-8acb-0f4788d589fb.png)

Works fine when there are 10 items for the legend for example....

**Comment by simonssspirit** [comment]
@tybshahid I assume that this occurs because the height is set to 250. When we render the legend with that many items, there is no space for the actual Chart to render. The Chart nearly unlimited number if series:

https://stackblitz.com/edit/react-ndz9ac?file=app/main.jsx

**Comment by kdikov82** [comment]
The only possible solution for this is changing the height and the width of the Chart and I am not sure that there could be any internal solution for this particular scenario. 

As a workaround you can set the ChartLegend width to some extreme value, so that only one column is rendered for the legend items, but this will prevent the rendering of all items.
