### ISSUE TITLE
DateTimePicker max date is not visually selected in the Calendar if there are hours specified in the max prop.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#782]
DateTimePicker max date is not visually selected in the Calendar if there are hours specified in the max prop.

https://www.telerik.com/kendo-react-ui/components/dateinputs/datetimepicker/date-ranges/#limiting-the-date-range

Steps:

1) Selected the date (March 3rd, 2002) from the Calendar.
2) Open it again and noticed how the date is not visually selected.

**Comment by kspeyanski** [comment]
The issue has been fixed in the latest `dev` version of the `@progress/kendo-react-dateinputs` package.
The fix can be observed in the `develop` version of the demo above:
https://www.telerik.com/kendo-react-ui-develop/components/dateinputs/datetimepicker/date-ranges/#limiting-the-date-range

For the full changelog, please refer to the [KendoReact Changelog page](https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/)
