### ISSUE TITLE
Grid - scroll remains visible even if grid does not have scroll

### ISSUE THREAD

**Issue by Nodios** [telerik/kendo-react#807]
Grid is displaying scroll bar even when it is not needed.

This can be seen on Grid Getting Started example. Slice products like this: ...products.slice(0, 5) in Grid.data.

Both header cell and scroll column are not hidden when they are not needed.

See image below:
<img width="287" alt="chrome_vNUEz7rtGS" src="https://user-images.githubusercontent.com/7250398/101896111-c45e7000-3ba8-11eb-8553-ef206618d490.png">

**Comment by simonssspirit** [comment]
The scroll will be displayed based on te scrollabe prop of the Grid, not based on the data:

https://www.telerik.com/kendo-react-ui/components/grid/api/GridProps/#toc-scrollable

**Comment by Nodios** [comment]
Yes, but in case you do need scroll you cannot use scrollable="none". Lets say that your data can range from 0 to 100,000 items all displayed without pager (so virtual scroll). In case you get 0 items back, your scroll column will still be visible. 

Plus, your basic grid example with scrollable="none" breaks apart.

![image](https://user-images.githubusercontent.com/7250398/102069879-a25e2b00-3dfe-11eb-9ec8-3200d0dd263d.png)

**Comment by kdikov82** [comment]
The scrollbar remains visible, because of the layout in the header adds additional space in the header to compensate for the scrollbar when scrolling is enabled. 

There are two ways of handling the requirement:
1) Disable the scrollable conditionally (based on the number of items or any other condition): https://stackblitz.com/edit/react-q8kvnl-939iwr?file=app%2Fmain.jsx
2) Add a className to the Grid conditionally and remove the scrollbar with CSS: https://stackblitz.com/edit/react-rv1awd-dytang?file=app%2Fmain.jsx
