### ISSUE TITLE
Switches behave incorrectly being initially rendered hidden

### ISSUE THREAD

**Issue by GeoMarkou** [telerik/kendo-react#81]
## I'm submitting a...
* Bug report

## Current behavior
Switches that are within a hidden div display incorrectly when clicked, and cause a JavaScript error when click-dragged.

## Expected behavior
Switch appears and behaves correctly after going from hidden to visible.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/react-qwyfmb
1. Create a Switch within a hidden div.
2. Change the hidden div to visible.
3. Try to use the Switch.

## What is the motivation or use case for changing the behavior?
We have forms that are tabbed. Sometimes Switches are initially rendered within a hidden tab, and then displayed to the user.

## Environment
Browser:
- Chrome (desktop) Version 68.0.3440.106 (Official Build) (64-bit)
- Firefox version 61.0.2 (64-bit)

System:
- Node version: v8.9.3
- Platform: Windows

**Comment by kspeyanski** [comment]
Hello @GeoMarkou 
Thank you for reporting this behaviour.

The Switch does calculate it's position relative to it wrapping element upon initial mount. Being mounted inside a hidden `div` does not allow it to properly calculate the size of the wrapper.
We have indeed identified this as bug, but i'm curious why would you need to render something in a hidden div, instead of using conditional rendering?

I have modified your example to use conditional rendering, so you can use this implementation as a work-around until we have fixed the bug:

[Switch with conditional rendering example](https://stackblitz.com/edit/react-qwyfmb-y4son5?file=app/main.js)

Providing a real-live use case where conditional rendering is not possible will help us better understand our customers needs, so i will kindly ask you to provide us with more information on how you came up to this problem.

For now i believe that calculating position on every update instead of on mount will introduce a performance problem for the Switch component. Any feedback is welcome!

Greetings,
Kiril

**Comment by kspeyanski** [comment]
Hello @GeoMarkou,

I believe i understand your use-case completely now.

I would like to share an implementation we use in-house for our [`TabStrip`](https://www.telerik.com/kendo-react-ui/components/layout/tabstrip/) component, which seems to be a perfect balance between initial render and post-update render _(at least for us)._

Initially we render only the selected tab, in your case the `div` that is shown by default. Whenever the user selects another tab, we render it, but apply `hidden` property to the first one.
This is some kind fo lazy loading for the tabs, which keeps the already rendered ones mounted.

I'll be closing this issue for now, but please let me know if you need further help.

Greetings,
Kiril
