### ISSUE TITLE
NVDA reads multiple months when focusing a value in the DatePicker.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#832]
NVDA reads multiple months when focusing a value in the DatePicker.

It should only read of the month of the focused date.

Tested on NVDA and Chrome  87.0.4280.141 (Official Build) (64-bit)

**Comment by kspeyanski** [comment]
The issue seems related to the `role` of the "Month label", which is also being __read__ by NVDA.
I'll play around with it, as i suspect that `role="presentantion"` is the correct one for this specific role, thus we will __hide__ it for the Screen Reader since it provides only visual separation of the months.

We'll write back once we test it out.

**Comment by kspeyanski** [comment]
The issue has been fixed in the latest version of the `@progress/kendo-react-dateinputs` package:
https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#41ea4d7e-c793-5aca-85bf-c06b34c82e2e
