### ISSUE TITLE
Grid's keyboard navigation get stuck if NVDA reader is turned on

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-react#887]
The navigation get stuck on the cells in the filter row - https://www.telerik.com/kendo-react-ui/components/grid/keyboard-navigation/.

Reason: There is a React keydown event, attached to the Grid's wrapping DIV element which is not triggered if NVDA reader is turned on.

Reproducible with an HTML table only - https://stackblitz.com/edit/react-3uuuxy-rk69gn?file=app%2Fmain.jsx 

Reproduced on Chrome, Windows 10

**Comment by vladimirivanoviliev** [comment]
Related to: https://github.com/telerik/kendo-react/issues/841

**Comment by vladimirivanoviliev** [comment]
Probably related: when navigating in browser mode throught cells in Grid, the cell value is readed but the column title is not.

**Comment by vladimirivanoviliev** [comment]
Part of the issue comes from that the software developers use the Screen readers differently than the users with disabilities. The difference lie in the readers two modes of operation:

- Browser mode - this mode is intended for navigation. Screen reader swallows events, and use it's own cursor for navigation position, without moving the browser focus.

- Focus mode - it's intended for interacting with editors only. It's incorrect to use this mode for navigation. What users with disabilities would do is to navigate to the editor they need with the screen reader browser mode,  enter focus mode to change the value, and then leave back to browser mode to continue navigation.

For more information on the matter you can check this article:

- https://www.accessibility-developer-guide.com/knowledge/screen-readers/desktop/browse-focus-modes/
