### ISSUE TITLE
NumericTextBox shows a different value in controlled mode

### ISSUE THREAD

**Issue by kkapitanova** [telerik/kendo-react#926]
The NumericTextBox shows a different value when in controlled mode and behaves differently than how the HTML input element does

The difference can be seen in the following example: 
https://stackblitz.com/edit/react-m1bmrg-z8radq?file=app/main.jsx 

How to reproduce: Try to enter a number that has more than 4 digits and see the difference in the behavior of both inputs

Reported in 1519116

**Comment by vladimirivanoviliev** [comment]
The reason why some restrictions are not applied on keyboard input and the validation is made on blur is because sometimes in order to enter a number that is valid, a user must first enter an invalid one. For example, if the min property is set to `5` and the user wants to enter the number `40`, the `NumericTextBox` should not prevent the user from typing `4` (even though it is smaller than 5), since this way the user would not be able to enter the correct value at all. This is the default behavior of the HTML input element, and since the NumericTextBox is based on it, the behavior of the NumericTextBox is the same. You can see how the default HTML input element behaves here: 
- https://www.w3schools.com/tags/att_input_min.asp
