### ISSUE TITLE
Allow multiple checkbox selection in Grid using getSelectedState and getSelectedStateFromKeyDown

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#937]
Allow multiple checkbox selection in Grid using getSelectedState and getSelectedStateFromKeyDown

Currently, the checkbox selection works only on a single selection with these methods.

**Comment by cr7yash** [comment]
Hi, is there any expected timeline for this enhancement? Or could you suggest a workaround if this is not going to be fixed in near future.

**Comment by Xizario** [comment]
In the demo here https://www.telerik.com/kendo-react-ui/components/grid/selection/#toc-customizing-the-selection
There should be different handling in case the checkbox is clicked or the row in the selectionChange event. And it would depend on the actual need. For example if you want the checkboxes to perform simple toggle, or you want to mimic something similar to the range selection. In both cases the demo should be fixed, rather than the method itself, which servers different purpose.

I could suggest you the correct implementation if you describe the wanted behaviour.

**Comment by simonssspirit** [comment]
The multiple selections with a checkbox can work if we directly update the items in the state based on the required result after click 2 different checkboxes.

@vladimirivanoviliev Please advise if this has to be handled by the new getSelectedState method, or has it to be done programmatically based on the required result?

**Comment by vladimirivanoviliev** [comment]
The demo is now fixed.
