### ISSUE TITLE
TileLayout's items improperly remounted (React)

### ISSUE THREAD

**Issue by mkrauskopf** [telerik/kendo-react#948]
* Bug report

TileLayout's items should not be remounted when `item`, `body`, or `header` properties are not changed

See the attached isolated example in [this Gist](https://gist.github.com/mkrauskopf/e23bad5f66ad641766c9c730577ff532) with the debug logging.

1) Open the example in the browser.
2) Click the _Change Mode_ button.

In the console, you will see mounted/unmounted messages. In the real world, the `useEffect` with `[]` dependencies are often used to do the "setup" work, fetching the data from the network, etc.

Due to this bug, the effects are run each time, the properties, like "reorderable", are changed. This causes quite user-visible problems in real-world applications.

**Comment by jancajthaml** [comment]
same issue

**Comment by silviyaboteva** [comment]
Hello @mkrauskopf and @jancajthaml,

We were able to reproduce the tiles' re-mounting issue after further debugging. It seems that the issue is with the dynamic prop changes, in this case with the `reorderable` prop. We located the issue and will provide a fix in the next dev version.

Thank you for bringing this to our attention!

**Comment by silviyaboteva** [comment]
As of `4.7.0-dev.202105282046` the issue is resolved.

**Comment by mkrauskopf** [comment]
I've just tried that with our use case and it works like a charm. Thanks for the quick fix!
