### ISSUE TITLE
Bar chart label not displaying fully if the width of chart is less.

### ISSUE THREAD

**Issue by vaisakhcp** [telerik/kendo-react#991]
I am using react kendo chart to create multiple bar charts. I am using ChartSeriesItem labels to show the value for each item. I am having 4 charts on my screen in a single row, so the width I am using is around 1/4th of screen for one chart. The value is not showing fully for larger values. I was able to reproduce the same in stackblitz when I reduce the screen width. A screenshot for the same is attached here.

<img width="1792" alt="Screenshot 2021-07-07 at 10 40 18 AM" src="https://user-images.githubusercontent.com/9795456/124703682-5ac0fd00-df10-11eb-80cd-5a15350dc36e.png">

 The stackblitz url also included bellow
 
 https://stackblitz.com/edit/react-cufm2g-awyfsf?file=app/main.jsx

The version of kendo I am using is 4.7.0.

**Comment by simonssspirit** [comment]
@vaisakhcp This is because there is no space for the label.

In those cases, we can suggest using one of the other available positions for the labels that will best cover the real application case:

https://www.telerik.com/kendo-react-ui/components/charts/api/SeriesLabelsPosition/

https://stackblitz.com/edit/react-cufm2g-q1tagv?file=app/main.jsx

Also, we recommend using our support system for issues like this, as we have 24 or 72 (based on the license) hours guaranteed response time.

We monitor the issues here as well, but sometimes, like in this case, we may miss it,
